### ISSUE TITLE
[neovim terminal & vim-autocomplpop] Strange behavior in Neovim's terminal mode

### ISSUE THREAD

**Issue by StavromulaBeta** [akinomyoga/ble.sh#232] opened 2022-09-14 19:13 UTC
**ble version**: 
0.4.0-devel3+793dfad
**Bash version**: 
5.2.0(1)-rc2 (x86_64-pc-linux-gnu)

While Ble.sh works fine now when running raw in my terminal emulator, i'm having some problems when I run it inside neovim's (0.7.2) terminal mode (`:terminal`). While I can run commands fine with highlighting and suggestions working perfectly, there are issues when entering insert mode. If I enter insert mode with `A` there is no problem, but if I use `a` or `i` then this is printed to the screen:

    make -C bleh.sh install PREFIX27_feedPopup()~/.local
    bash: syntax error near unexpected token `('
    [ble: exit 2]

This message is highlighted correctly, and after it prints I can type commands and everything still seems to be working.

**Comment by akinomyoga** [comment] 2022-09-15 03:03
Thank you for the report! As far as I try, the problem doesn't seem to reproduce. Does it happen with the plain settings of neovim in your environment? I have tried it with nvim 0.7.2 and bash 5.2.0(1)-rc2 with plain settings plus ble.sh and `set -o vi`, but I don't see any problems in using `a` and `i`.

**Comment by akinomyoga** [comment] 2022-09-15 03:28
Could you udpate your `acp` plugin (AutoComplPop / vim-autocomplpop) to the latest version?
- https://github.com/othree/vim-autocomplpop
- https://github.com/vim-scripts/L9 (you may additionally need to install this L9 library)

----

When I searched for the string `_feedPopup()`, I found some [reports](https://askubuntu.com/questions/382407/vim-autocomplpop-issues) about vim.  The error message `_feedPopup()` seems to be related to a vim plugin `AutoComplPop` (`acp`).  I could reproduce the problem after installing `acp` (~/.config/nvm/autoload/acp.vim, ~/.config/nvm/plugin/acp.vim, etc.). But the problem seems to happen at a certain condition even without ble.sh. I think this issue is unrelated to ble.sh. Later, I found [another report](https://github.com/othree/vim-autocomplpop/issues/9) at another repository of `acp`, where the problem seems to be already fixed.  The repository [`othree/vim-autocomplpop`](https://github.com/othree/vim-autocomplpop/issues/9) seems to be the currently maintained version of `AutoComplPop`.  In fact, this version doesn't have the problem as far as I try.

**Comment by StavromulaBeta** [comment] 2022-09-15 09:53
ah yes that seems to fix it - again I should have done my own research before submitting this issue. Sorry and thank you!!!

**Comment by akinomyoga** [comment] 2022-09-15 10:32
Thanks! I'm closing it.

**Closed by akinomyoga** 2022-09-15 10:32 UTC
Labels: External Bug
