### ISSUE TITLE
Conflict with nRF Connect extenstion of VSCode

### ISSUE THREAD

**Issue by liyafe1997** [akinomyoga/ble.sh#392] opened 2024-01-25 10:15 UTC
**ble version**: 0.4.0-devel4+29cd8f1
**Bash version**: 5.1.16(1)-release (x86_64-pc-linux-gnu)

Disto: Ubuntu 22.04 
VSCode version: 1.85.2

Problem: If `ble.sh` enabled, the nRF Connect extension doesn't work (always keep and stuck at loading), and I can see a `bash -i` process takes so much CPU. With `ble.sh` disabled that extension works well. I guess `ble.sh` blocks some commands that the extension runs from bash.

![图片](https://github.com/akinomyoga/ble.sh/assets/18359157/7952368b-59dc-470b-bf66-38cd602967b7)

nRF Connect extension version:

![图片](https://github.com/akinomyoga/ble.sh/assets/18359157/02e06f4f-05c5-4aac-bb59-62f396a96ce0)

**Comment by akinomyoga** [comment] 2024-01-28 09:51
> Problem: If `ble.sh` enabled, the nRF Connect extension doesn't work (always keep and stuck at loading),

Thank you for the report, but could you explain it in more detail? I took time to install *nRF Connect for the VS Code Extension Pack* in VS Code and then restarted VS Code. But I'm not sure what to do next. Apparently, nothing seems to happen by just restarting VS Code, so I guess something needs to be attempted by user by using the nRF extension. You say "it doesn't work", but to see that it doesn't work what can I do and how can I judge if it works or not? Could you explain to me where to start?

**Comment by liyafe1997** [comment] 2024-01-30 08:22
> > Problem: If `ble.sh` enabled, the nRF Connect extension doesn't work (always keep and stuck at loading),
> 
> Thank you for the report, but could you explain it in more detail? I took time to install _nRF Connect for the VS Code Extension Pack_ in VS Code and then restarted VS Code. But I'm not sure what to do next. Apparently, nothing seems to happen by just restarting VS Code, so I guess something needs to be attempted by user by using the nRF extension. You say "it doesn't work", but to see that it doesn't work what can I do and how can I judge if it works or not? Could you explain to me where to start?

Click the nRF Connect icon on the left panel, then you can see it always keep loading forever, and now `bash -i` takes 100% CPU.

**Comment by akinomyoga** [comment] 2024-01-30 08:27
Thanks! I'll try that later when I come back home today.

**Comment by akinomyoga** [comment] 2024-01-31 22:49
I could reproduce the problem and added a workaround to it in commit 2df3b109. I confirmed that the problem is fixed in my environment. @liyafe1997 Could you update ble.sh by running `ble-update` in a ble session and check if the problem is fixed in your environment?

### What was happening

Here, I summarize the result of the investigation into the issue. It turned out the nRF Connect tries to extract a setting in an interactive session by starting Bash with an interactive session (i.e., a session with a line editor support) in the background and sending the following commands to the background Bash:

```bash
 unset HISTFILE
 echo ZEPHYR_BASE=${ZEPHYR_BASE}
 exit
```

However, ble.sh has protection against pasting multiline contents; when it detects that a multiline text is input at once, it enters the multiline mode instead of immediately running the pasted commands. This is because users can sometimes mistakenly paste a large volume of text into the terminal, but we want to avoid running those random texts as *commands*. ble.sh does not execute those multiline texts immediately but instead inserts the texts into the command line and asks the user to explicitly run it by pressing <kbd>C-j</kbd>.

By this protection feature, the commands sent by nRF Connect are blocked by ble.sh.

So far, nRF Connect doesn't seem to actually use the feature of the line editor, so I decided to just disable ble.sh when it detects nRF Connect.

**Comment by liyafe1997** [comment] 2024-02-01 13:44
I am not sure this is a good solution for just make a specific workaround for a specific case. Is it possible to identity the "multi-line input" is from a real console or it is passed from pipe by a program or something?

**Comment by akinomyoga** [comment] 2024-02-05 16:00
I remembered that stderr of the Bash started by nRF Connect was not connected to TTY, so I again took time to look at it.

It seems the Bash started by nRF Connect has an associated control terminal, yet its standard streams are all connected to some sockets. Then, I was wondering what would be the point that the control terminal is assigned to the Bash process.

Finally, I realized that I can use the `ps` command to correctly show the information of the TTY associated with the process. (the `tty` command was useless because it just shows something like `/dev/tty` for processes that don't have the original file descriptors connected to the terminals). It is typically like this:

```
murase   27902  0.0  0.0   2888   992 pts/1    Ss   00:43   0:00 sh -c "$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" 05047486b6df5eb8d44b2ecd70ea3bdf775fd937 stable code-server .vscode-server --host
murase   27903  0.0  0.0   2888   960 pts/1    S    00:43   0:00  \_ sh /mnt/c/Users/murase/.vscode/extensions/ms-vscode-remote.remote-wsl-0.86.0/scripts/wslServer.sh 05047486b6df5eb8d44b2ecd70ea3bdf7
murase   27908  0.0  0.0   2888   968 pts/1    S    00:43   0:00      \_ sh /home/murase/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/bin/code-server --host=127.0.0.1 --port=0 --connect
murase   27959 65.5  3.4 967480 135240 pts/1   Sl   00:43   0:07          \_ /home/murase/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node /home/murase/.vscode-server/bin/05047486b6df5
murase   28056 62.0  4.8 1034640 191928 pts/1  Rl   00:43   0:04              \_ /home/murase/.vscode-server/bin/05047486b6df5eb8d44b2ecd70ea3bdf775fd937/node --dns-result-order=ipv4first /home/murase
murase   28104  0.0  0.5 398036 20588 pts/1    Rl   00:43   0:00                  \_ /home/murase/.vscode-server/extensions/nordic-semiconductor.nrf-connect-2023.11.301/platform/nrfutil/bin/nrfutil-de
murase   28111  0.0  0.0   2888   948 pts/1    S    00:43   0:00                  \_ /bin/sh -c /bin/bash -i
murase   28114  0.0  0.0   7472  3672 pts/1    S+   00:43   0:00                      \_ /bin/bash -i
murase   28116  0.0  0.0  10040  1560 pts/1    R+   00:43   0:00                          \_ ps uxf
```

This means that the TTY is not actually assigned by the nRF Connect extension but seems to be assigned by the framework of the VS Code extension. Then the question here is that when the standard streams are connected to something other file descriptors, should we disable ble.sh? I actually intentionally tried to make ble.sh work even in that case by connecting to the original TTY through `/dev/tty`. That is useful when I debug terminal emulators, and I also wanted to share it as the feature of ble.sh.

**Comment by akinomyoga** [comment] 2024-02-05 16:03
@liyafe1997 As far as I run many times the initialization of nRF Connect in VS Code, the problem of loading the nRF Connect doesn't seem to happen. Could you check if that is the same in your environment with the latest version of ble.sh? Or do you still have the problem that the loading of nRF Connect doesn't finish?

**Comment by liyafe1997** [comment] 2024-02-06 10:42
Yes it works now. Thank you!

**Comment by akinomyoga** [comment] 2024-02-06 11:11
Thank you!

After your comment https://github.com/akinomyoga/ble.sh/issues/392#issuecomment-1921357912, I'm now thinking about the possibility of changing the condition `! ((1)) >/dev/tty` on [the TTY check](https://github.com/akinomyoga/ble.sh/commit/2df3b1096c1c19bc149e4da3450b24c29bf4d8c9#diff-e80de13d3da9c164e1f38fa3ffa59ee80f139cd464d402d1abe703802fe6d0a9R200). This condition checks the existence of the controlling terminal in the current session. As I've described above, as far as there is a controlling terminal associated with the current session, ble.sh connects to the controlling terminal while keeping the original stdout/stderr/stdin for user commands.

However, it may cause a problem when the caller of Bash (such as *nRF Connect*) intentionally makes the line editor communicate with non-TTY streams. I haven't assumed such a situation until this report and I feel such usage is a hack, but it is still technically possible. Maybe I need to give up an idea to ensure ble.sh to communicate with the controlling terminal. I think I can make it an opt-in feature.

**Comment by akinomyoga** [comment] 2024-02-06 11:12
Anyway, it is going to be off-topic in this thread, so let me close the issue. Thank you again for the report and responses!

**Closed by akinomyoga** 2024-02-06 11:12 UTC
Labels: compatibility
