### ISSUE TITLE
[empty locale] Autocomplete gets added after the prompt when using starship

### ISSUE THREAD

**Issue by Ultra980** [akinomyoga/ble.sh#269] opened 2023-01-28 07:45 UTC
**ble version**: 0.4.0-devel3+e3cdb9d 
**Bash version**: 5.2.15(1)-release (x86_64-suse-linux) 

**Output of `[Ctrl-X] [Ctrl-V]`**:
* In the distrobox:
```
GNU bash, version 5.2.15(1)-release (x86_64-suse-linux) [openSUSE Tumbleweed]
ble.sh, version 0.4.0-devel3+e3cdb9d (noarch) [git 2.39.0, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:37a0fec4e27779dc87253aa7f27cfa8d14d6a4a6, 77846 bytes) (noarch)
starship, version 1.12.0-master (rustc 1.65.0 (897e37553 2022-11-02), 2022-12-13 16:12:30 +00:00)
locale:
terminal: TERM=xterm-256color wcwidth=4.1-west/15.0-2+ri, xterm:115 (1;115;0)
```

* On bare metal:
``` 
GNU bash, version 5.2.15(1)-release (x86_64-suse-linux) [openSUSE MicroOS]
ble.sh, version 0.4.0-devel3+e3cdb9d (noarch) [git 2.39.0, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:37a0fec4e27779dc87253aa7f27cfa8d14d6a4a6, 77846 bytes) (noarch)
starship, version 1.12.0-master (rustc 1.65.0 (897e37553 2022-11-02), 2022-12-13 16:12:30 +00:00)
locale: LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-musl/15.0-2+ri, xterm:115 (1;115;0)
```

When I type a command into the prompt, if it has suggestions for completing the command they get put after the prompt. For example, if I type `ca` ble.sh tries to autocomplete with `cat` but it adds `cat` after the already written command, resulting in `cacat`. I would send a recording with `asciinema`, but the issue seems to go away when I start recording (with `asciinema rec error.cast`). 
This only happens when I'm inside a `distrobox` container, not on the host system.
I don't know if this is related, but I'm using the [starship](https://starship.rs) prompt with the following config:

```toml
format = """
[ ](bg:#4ab0bb)\
[ ](bg:#5bc0cc)\
[ ](bg:#6cd0dd)\
[ ](bg:#7de0ee)\
[   ](bg:#8ef0ff fg:#090c0c)\
[](bg:#1692a4 fg:#8ef0ff)\
$directory\
[](fg:#1692a4 bg:#006d7d)\
$git_branch\
$git_status\
[](fg:#006d7d bg:#004b5b)\
$container\
[](fg:#004b5b bg:#003a4a)\
$sudo\
[](fg:#003a4a bg:#003740)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:#003740 bg:#00171b)\
$time\
$status\
[ ](fg:#00171b)
[ ](bg:#4ab0bb)\
[](fg:#5bc0cc)  """

[directory]
style = "fg:#bef6ff bg:#1692a4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#1692a4 bg:#006d7d"
format = '[[ $symbol $branch ](fg:#1692a4 bg:#006d7d)]($style)'

[git_status]
style = "fg:#1692a4 bg:#006d7d"
format = '[[($all_status$ahead_behind )](fg:#1692a4 bg:#006d7d)]($style)'

[nodejs]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[rust]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[php]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[python]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#00171b"
format = '[[  $time ](fg:#bef6ff bg:#00171b)]($style)'

[container]
symbol = ""
style = "fg:#bef6ff bg:#004b5b"
format = '[ $symbol $name ]($style)'

[status]
disabled = false
style = "bg:#00171b"
success_symbol = '[](fg:#00ff00 bg:#00171b)'
symbol = '[](fg:#ff0000 bg:#00171b)'
format = "[ $symbol $status ]($style)"

[sudo]
symbol = ""
style = "bg:#003b4b"
format = "[ $symbol ]($style)"
disabled = false
```

**Comment by akinomyoga** [comment] 2023-01-28 08:42
> - In the distrobox:
> ...
>
> ```
> terminal: TERM=xterm-256color wcwidth=4.1-west/15.0-2+ri, xterm:115 (1;115;0)
> ```

The `wcwidth` routine used by the terminal seems to be based on Unicode 4.1 or some non-Unicode character-width scheme. This implies that the C library of `distrobox` is so old (or incompatible) that it doesn't support the proper character widths of Emojis and recent Unicode characters, which are used by Starship. Then, there is a mismatch between the widths assumed by the terminal and Starship. This causes an issue in the calculation of the cursor positions.

Currently, ble.sh attempts to select the scheme used by the terminal. For the time being, maybe you could try overriding the character-width scheme of ble.sh to match it with Starship by the following setup:

```bash
# ~/.blerc
bleopt char_width_version=15.0
```

But, of course, the mismatch between the terminal and Starship is not solved by the ble.sh settings, so this might still cause glitches in other situations.

**Comment by Ultra980** [comment] 2023-01-28 08:55
Thanks for the reply!

> This implies that the C library of `distrobox` is so old (or incompatible) that it doesn't support the proper character widths of Emojis and recent Unicode characters, which are used by Starship

Hmmm, it's just tumbleweed in a container, this shouldn't happen... I tried running `sudo zypper dup` but `glibc` was up-to-date.


> Currently, ble.sh attempts to select the scheme used by the terminal. For the time being, maybe you could try overriding the character-width scheme of ble.sh to match it with Starship by the following setup:
> 
> ```shell
> # ~/.blerc
> bleopt char_width_version=15.0
> ```

This didn't work :(

**Comment by akinomyoga** [comment] 2023-01-28 09:10
It seems the `musl` C library recently updated the character width of `wcwidth`.

- [musl - musl - an implementation of the standard library for Linux-based systems](https://git.musl-libc.org/cgit/musl/commit/src/ctype/wcwidth.c?id=70d80609558153a996833392999c69cdb74e1119)

Maybe because of this, ble.sh fails to detect the new version of `musl` wcwidth. The `musl` wcwidth implementation is actually non-Unicode and causing problems. It tries to be *clever* to cover the widths of "most" Unicode characters by a simplified table, but I have to say "mostly" Unicode `wcwidth` is non-Unicode `wcwidth`. For this reason, ble.sh detects `musl` as an exceptional wcwidth scheme, but I haven't been tracking minor updates of `musl`.

> I tried running sudo zypper dup but glibc was up-to-date.

There is a choice for the underlying system C library when one installs openSUSE Tumbleweed. As far as I remember, with the default choice of the openSUSE distribution, the system C library is this strange C library `musl`. You can install glibc on top the distribution, but I'm not sure which C library your terminal uses finally.

Anyway, I'll later check if the problem reproduces in the latest Tumbleweed and try to implement the detection of the new musl wcwidth. (I'm now waiting for `sudo zypper dup` in my copy of openSUSE Tumbleweed in a virtual machine. It seems to take a long time because I left it for a very long time).

**Comment by akinomyoga** [comment] 2023-01-28 09:49
It seems `musl` is unrelated here. The openSUSE Tumbleweed doesn't use `musl`. ble.sh seems to fail to detect it with Unicode version 15.0.

**Comment by akinomyoga** [comment] 2023-01-30 05:34
I tried your starship settings in the latest openSUSE Tumbleweed in konsole, but the problem doesn't seem to reproduce exactly.

Now I noticed that your `distrobox` in https://github.com/akinomyoga/ble.sh/issues/269#issue-1560741418 doesn't have locale settings. This line:

> ```
> locale:
> ```

When I manually set `LANG=` in my environment and restart Bash with ble.sh, I can see similar problems when I enter the multiline editing mode (yet the very problem reported with auto-complete doesn't seem to reproduce).

- **Q1**: Could you set a UTF-8 locale in your ~/.bashrc (such as `LANG=C.UTF-8` or `LANG=en_US.UTF-8`) and see if the situation changes?

**Comment by akinomyoga** [comment] 2023-01-30 13:25
OK, thank you for checking! If the locale variables are not set, I think there is no way to detect if the terminal under that system has UTF-8 support or not. I wouldn't try to fix it at the ble.sh side, but maybe ble.sh could print some warning messages about suspicious locale settings on the startup.

**Comment by Ultra980** [comment] 2023-01-30 17:45
Sometimes the .bashrc doesn't set the `$LANG` variable...

**Comment by akinomyoga** [comment] 2023-01-30 18:07
Actually, `LANG` and other locale variables are normally set by the operating system, so `~/.bashrc` and other configurations usually do not need to set these variables.

One exception is when one wants to use locale settings that are different from the ones provided by the system, where one can overwrite the locale variables in `~/.bashrc` or other setups. In your `distrobox`, the system seems to provide the empty locale (which I believe is unusual), so we may overwrite it in `~/.bashrc`.

Another case that one needs to set the locale variables manually is when one wants to start a session with `env -i` where all the environment variables are cleared. In this case, one should specify the locale variables separately like `env -i LANG=... command`.

**Comment by akinomyoga** [comment] 2023-01-31 10:14
> I wouldn't try to fix it at the ble.sh side, but maybe ble.sh could print some warning messages about suspicious locale settings on the startup.

I implemented this in commit 7da9bce.

**Comment by akinomyoga** [comment] 2023-02-01 16:08
> This means that ble.sh's detection is wrong even for your _bare metal_ environment. It seems to fail to detect it with Unicode version 15.0.

I added a fix to the `musl` detection in commit b0c16ddc00d249b6392bfeaf9b9ba091f32aa095.

**Comment by akinomyoga** [comment] 2023-02-08 14:30
@Ultra980 I guess there is no further issue. Can I close the issue?

**Comment by akinomyoga** [comment] 2023-03-15 23:54
@Ultra980

**Closed** 2023-03-16 07:44 UTC
Labels: compatibility

**Comment by akinomyoga** [comment] 2023-03-16 08:12
Thank you for your reply. Yeah, we still need to ask users to set any locale to make it work. Nevertheless, `ble.sh` can't determine which locale should be used, so I decided to make it just show the warning message on its startup as commented at https://github.com/akinomyoga/ble.sh/issues/269#issuecomment-1410092991. Thank you again for reporting the issue.
