### ISSUE TITLE
bash: ü: invalid variable name

### ISSUE THREAD

**Issue by ghost** [akinomyoga/ble.sh#119] opened 2021-06-03 06:43 UTC
**ble version**: 0.4.0-devel3+0e55b8e
**Bash version**: 5.1.8(1)-release

When there's a parameter expansion or definition with an invalid name that output gets printed in the command line, when it would better to see it when the command is executed and don't interrupt typing. Examples when in happens:

`$übash: ü: invalid variable name`
`${ábash: á: invalid variable name`
`è=bash: è: invalid variable name`

**Comment by akinomyoga** [comment] 2021-06-03 07:17
Thank you for the report! Confirmed. Interestingly, I found that the behavior of the regular expressions differs among systems and locales. I'll fix it later.

```bash
# In Linux (Fedora 31)

[murase@chatoyancy 1 ble.sh]$ LANG=ja_JP.UTF-8
[murase@chatoyancy 1 ble.sh]$ shopt -s globasciiranges
[murase@chatoyancy 1 ble.sh]$ [[ 'ü' =~ [a-z] ]]; echo $?
1
[murase@chatoyancy 1 ble.sh]$ shopt -u globasciiranges
[murase@chatoyancy 1 ble.sh]$ [[ 'ü' =~ [a-z] ]]; echo $?
1
[murase@chatoyancy 1 ble.sh]$ LANG=en_US.UTF-8
[murase@chatoyancy 1 ble.sh]$ shopt -s globasciiranges
[murase@chatoyancy 1 ble.sh]$ [[ 'ü' =~ [a-z] ]]; echo $?
0
[murase@chatoyancy 1 ble.sh]$ shopt -u globasciiranges
[murase@chatoyancy 1 ble.sh]$ [[ 'ü' =~ [a-z] ]]; echo $?
0

# In Cygwin

[murase@vaio2016 0 src]$ LANG=ja_JP.UTF-8
[murase@vaio2016 0 src]$ shopt -s globasciiranges
[murase@vaio2016 0 src]$ [[ 'ü' =~ [a-z] ]]; echo $?
0
[murase@vaio2016 0 src]$ shopt -u globasciiranges
[murase@vaio2016 0 src]$ [[ 'ü' =~ [a-z] ]]; echo $?
0
[murase@vaio2016 0 src]$ LANG=en_US.UTF-8
[murase@vaio2016 0 src]$ shopt -s globasciiranges
[murase@vaio2016 0 src]$ [[ 'ü' =~ [a-z] ]]; echo $?
0
[murase@vaio2016 0 src]$ shopt -u globasciiranges
[murase@vaio2016 0 src]$ [[ 'ü' =~ [a-z] ]]; echo $?
0
```

What is your system (`$MACHTYPE` as in the issue template).

**Comment by akinomyoga** [comment] 2021-06-05 13:09
I pushed a fix e87ac21. It seems your GitHub account has been deleted, but if you have a new account, could you check if the problem is fixed? Thank you.

**Comment by oc1024** [comment] 2021-06-17 18:38
I vote for this issue being closed - compared a version before and after the commit in my package cache. Version before the commit has the issue, version after the commit doesn't.

**Comment by akinomyoga** [comment] 2021-06-17 19:42
Oh, thank you for the testing. OK! I'll close it.

**Closed by akinomyoga** 2021-06-17 19:42 UTC
Labels: bug
