### ISSUE TITLE
Multiline with open quotes and new emptylines

### ISSUE THREAD

**Issue by alborotogarcia** [akinomyoga/ble.sh#120] opened 2021-06-04 02:56 UTC
**ble version**:0.4.0-devel3+0e55b8e 
**Bash version**:5.1.8(1)-release (x86_64-pc-linux-gnu) 

echo "test1
test2
test3 "
echo test4

echo test5 # anything here throws an error even comments

Output:
test1
test2
test3
test4
bash: $'\recho': command not found
[ble: exit 127]

Expected Output:
test
test1
test2
test3
test4
test5

Kudos to everyone making ble possible awesome project!

**Comment by alborotogarcia** [comment] 2021-06-04 03:03
FYI I forgot to mention, it works as expected if there's no new emptyline..

**Comment by akinomyoga** [comment] 2021-06-04 04:25
Thank you for the report! I cannot reproduce the behavior. The error message implies that a CR (aka `^M` / `RET` / `\r`) strayed into the executed command-line string. I have questions.

- **Q1**: Does it reproduce with plain Bash and plain ble.sh?

```bash
$ INPUTRC=/dev/null bash --norc --noprofile        # Start plain bash
$ source /path/to/ble.sh --norc               # Start plain ble.sh
```

- **Q2**: After the error what is the result of `history | tail | cat -v`:

```bash
$ echo "test1
test2
test3 "
echo test4

echo test5
test1
test2
test3
test4
bash: $'\recho': command not found
[ble: exit 127]
$ history | tail | cat -v
```

- **Q3**: After exiting the session, what is the result of `tail ~/.bash_history | cat -v`

```bash
$ tail ~/.bash_history | cat -v
```

**Comment by alborotogarcia** [comment] 2021-06-04 14:49
**Q1**
```
(base) [alvaro@stealth ~]$ INPUTRC=/dev/null bash --norc --noprofile 
bash-5.1$ source /usr/share/blesh/ble.sh --norc
bash-5.1$ 
^Mecho "test1
test2
test3 "
echo test4
^Mecho test5 # anything here throws an error even comments
bash: $'\recho': command not found
test4
bash: $'\recho': command not found
[ble: exit 127]
bash-5.1$ 
```

**Q2**

```
source /usr/share/blesh/ble.sh --norc
eval -- $'^Mecho "test1\ntest2\ntest3 "\necho test4\n^Mecho test5 # anything here throws an error even comments'

```

**Q3**

```
  501  INPUTRC=/dev/null bash --norc --noprofile 
  502  
^Mecho "test1
test2
test3 "
echo test4
^Mecho test5 # anything here throws an error even comments


```

**Comment by akinomyoga** [comment] 2021-06-04 19:29
OK, thank you for the results. Ah, OK. I noticed there is a wrong description in README. The newline needs to be input by <kbd>C-v C-j</kbd> or <kbd>C-q C-j</kbd>.

- **Q5**: How do you input the newlines? Do you input them by <kbd>C-v RET</kbd> or <kbd> C-q RET</kbd>?

**Comment by alborotogarcia** [comment] 2021-06-04 19:36
@akinomyoga C-v RET from clipboard, though I've just check that it works if I manually introduce on multiline mode newlines

**Comment by alborotogarcia** [comment] 2021-06-04 19:37
@akinomyoga C-v RET from clipboard, though I've just checked that it works if I manually introduce on multiline mode newlines

**Comment by alborotogarcia** [comment] 2021-06-04 19:39
I mean first copy pasting with C-v RET
`echo "test1
test2
test3 "
echo test4`
then introducing \n
and maybe some other text
and then C-j

**Comment by akinomyoga** [comment] 2021-06-04 19:46
> I mean first copy pasting with C-v RET

What does it mean? Actually, <kbd>C-v RET</kbd> is not the paste in ble.sh but is \<input literal RET\>. Do you mean, you first paste texts and then press <kbd>C-v RET</kbd>?

**Comment by alborotogarcia** [comment] 2021-06-04 19:52
@akinomyoga sorry C-V for pasting text from clipboard to terminal/tmux..

**Comment by akinomyoga** [comment] 2021-06-04 19:57
Hmm, I'm confused. So you actually didn't send <kbd>C-v</kbd> to ble.sh, but <kbd>C-v</kbd> is processed by terminal as the pasting? I have further questions:

- **Q5**: What is your terminal? It seems that your operating system is Linux. What is the distribution?

> ```bash
> bash-5.1$ 
> ^Mecho "test1
> test2
> test3 "
> echo test4
> ^Mecho test5 # anything here throws an error even comments
> ```

- **Q6**: The above command line is different from your first report. Are `^M` shown every time or sometimes not shown?

**Comment by akinomyoga** [comment] 2021-06-04 20:05
I cannot still reproduce the behavior by text pasting using my terminals. I need to check the data sent from your terminal while pasting, which can be extracted by surrounding the operations by the commands `ble/debug/keylog#start` and `ble/debug/keylog#end`.

- **Q7**: What is the result of the following commands (with `echo ... test4` pasted from clipboard)?

```bash
$ ble/debug/keylog#start
$ echo "test1
test2
test3 "
echo test4

echo test5
(outputs / error messages from the command)
$ ble/debug/keylog#end
```

**Comment by alborotogarcia** [comment] 2021-06-04 20:06
**Q5** @akinomyoga yes I'm on arch linux and using xfce4-terminal//tmux
**Q6** Yes ^M always appears if and only if there's a newline above in the clipboard text
eg.  copy the text between `` with 2 newlines (just checked it works with only one newline before echo tes1)
`


echo test1
`
shows before C-j 
(base) [alvaro@stealth ~]$
^Mecho test1
-- MULTILINE -- (RET or C-m: insert a newline, C-j: run)

**Comment by alborotogarcia** [comment] 2021-06-04 20:09
@akinomyoga **Q7**
```

(base) [alvaro@stealth ~]$  ble/debug/keylog#start
(base) [alvaro@stealth ~]$ echo "test1
test2
test3 "
echo test4
^Mecho test5
test1
test2
test3 
test4
bash: $'\recho': command not found
[ble: exit 127]
(base) [alvaro@stealth ~]$ 


```

**Comment by akinomyoga** [comment] 2021-06-04 20:11
> **Q5** @akinomyoga yes I'm on arch linux and using xfce4-terminal//tmux
> **Q6** Yes ^M always appears if and only if there's a newline above in the clipboard text

OK, I try to reproduce the problem with xfce4-terminal/tmux.

> @akinomyoga **Q7**

Thanks, but I'm interested in the output of `ble/debug/keylog#end` after the trouble.

**Comment by alborotogarcia** [comment] 2021-06-04 20:12
@akinomyoga sure I forgot it thank you
`(base) [alvaro@stealth ~]$ ble/debug/keylog#end
===== bytes =====
192 155 91 50 48 48 126 101 99 104 111 3
2 34 116 101 115 116 49 13 116 101 115 1
16 50 13 116 101 115 116 51 32 34 13 101
 99 104 111 32 116 101 115 116 52 13 13 
101 99 104 111 32 116 101 115 116 53 192
 155 91 50 48 49 126 10 192 155 91 50 48
 48 126 98 108 101 47 100 101 98 117 103
 47 107 101 121 108 111 103 35 101 110 1
00 192 155 91 50 48 49 126 13

===== chars =====
ESC [ 2 0 0 ~ e c h o SP " t e s t 1 RET
 t e s t 2 RET t e s t 3 SP " RET e c h 
o SP t e s t 4 RET RET e c h o SP t e s 
t 5 ESC [ 2 0 1 ~ LF ESC [ 2 0 0 ~ b l e
 / d e b u g / k e y l o g # e n d ESC [
 2 0 1 ~ RET

===== keys =====
paste_begin C-j paste_begin C-m
`

**Comment by akinomyoga** [comment] 2021-06-04 20:25
OK! I could reproduce it. The problem is that some terminals seem to send `RET` (carriage return `\r`) instead of `LF` (newline / line feed `\n`). I'll take a look at what other terminals do and how to work around this behavior.

FYI, my terminal sends the following data, in which you can see the newlines are sent by `\n` (`LF`) but not by `\r` (`RET`):

```bash
$ ble/debug/keylog#end
===== bytes =====
192 155 91 50 48 48 126 101 99 104 111 3
2 34 116 101 115 116 49 10 116 101 115 1
16 50 10 116 101 115 116 51 34 10 116 10
1 115 116 52 10 10 116 101 115 116 53 19
2 155 91 50 48 49 126 13 127 10 98 108 1
01 47 100 101 98 103 127 117 103 47 107
101 121 108 111 103 35 101 110 100 13

===== chars =====
ESC [ 2 0 0 ~ e c h o SP " t e s t 1 LF
t e s t 2 LF t e s t 3 " LF t e s t 4 LF
 LF t e s t 5 ESC [ 2 0 1 ~ RET DEL LF b
 l e / d e b g DEL u g / k e y l o g # e
 n d RET

===== keys =====
paste_begin C-m C-? C-j b auto_complete_
enter l e / d e b g g C-? u auto_complet
e_enter g / k e y l o g # e e n auto_com
plete_enter d C-m C-m
```

**Comment by alborotogarcia** [comment] 2021-06-04 20:35
@akinomyoga I'm glad you could reproduce it.. Do you suggest to stick with gnome terminal? or are there any alternatives? 

I usually have some issues with Gtk3, x11 and nvidia, that's why I use xfce wherever I can

**Comment by akinomyoga** [comment] 2021-06-04 20:54
Actually, GNOME terminal has the same issue. GNOME terminal and xfce4-terminal are both based on libvte (VTE), so essentially the terminal behavior of the two terminals are the same. I think VTE modifies the pasted text so that terminal applications without the support of "Bracketed Paste Mode" aren't confused, which is the source of the problem. I found the same issue of Vim:

- https://github.com/vim/vim/issues/1404

I'm not looking at the code of VTE whether there is a discussion or a remark on this behaviour. Maybe I finally add some option to turn off bracketed paste mode or add a workaround for VTE. Or, maybe I should add a `bleopt` option to convert `RET` back to `LF` (though we cannot input `^M` in this setting).

**Comment by akinomyoga** [comment] 2021-06-04 21:18
Identified the commit: https://gitlab.gnome.org/GNOME/vte/-/commit/a062c6306732e1cfc034c0c49f416b09b93d63d0

The behavior of `vte` changing newlines (LF) to carriage returns (CR/RET) seems to be just a workaround for pico. I would say this is a bug of pico setting up bracketed paste mode without properly handling newlines (LF). Now I don't see the rationale for sending carriage returns instead of newlines, so I will support it in ble.sh as a *workaround for `vte`*.

**Comment by akinomyoga** [comment] 2021-06-04 22:07
I pushed a fix 8d6da16. I actually realized that ble.sh had already a workaround but it didn't completely work, which was the reason that the problem occurred only with empty lines. Could you check if the problem has been fixed? You can update `ble.sh` by `ble-update` in a ble.sh session. Thank you

**Comment by alborotogarcia** [comment] 2021-06-04 22:43
Great news @akinomyoga ! Yes completely working!
```
(base) [alvaro@stealth production]$  ble/debug/keylog#start
(base) [alvaro@stealth production]$ echo "test1
test2
test3 "
echo test4

echo test5
test1
test2
test3 
test4
test5
```
Truly appreciate it @akinomyoga !

**Comment by akinomyoga** [comment] 2021-06-04 22:46
Great! Thanks again for the report! I close the issue.

**Closed by akinomyoga** 2021-06-04 22:46 UTC
