### ISSUE TITLE
Broken navigation in multiline mode with tabs?

### ISSUE THREAD

**Issue by dgudim** [akinomyoga/ble.sh#396] opened 2024-01-30 07:53 UTC
**ble version**:
**Bash version**:

```
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu) [EndeavourOS]
ble.sh, version 0.4.0-devel4+50d6f1bb (noarch) [git 2.43.0, GNU Make 4.4.1, GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.11 (hash:2d02f73e803daa87a06e94e33b2a7b3e672a2c0c, 76338 bytes) (noarch)
fzf key-bindings, (hash:c4dce3ba5bfafecbc6c47695f89ef02c305b984e, 5524 bytes) (noarch) (integration: on)
fzf completion, (hash:db84e06a1ee5fb43bc6ad1aaeec6657cad79c917, 14523 bytes) (noarch) (integration: on)
atuin, version 17.2.1 (/usr/bin/atuin)
locale: LANG=en_US.UTF-8 LC_ADDRESS=en_US.UTF-8 LC_IDENTIFICATION=en_US.UTF-8 LC_MEASUREMENT=C LC_MONETARY=lt_LT.UTF-8 LC_NAME=en_US.UTF-8 LC_NUMERIC=en_US.UTF-8 LC_PAPER=en_US.UTF-8 LC_TELEPHONE=en_US.UTF-8 LC_TIME=ru_RU.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, konsole:220380 (1;115;0)
```

Look in the video.
1. Function indented with spaces
2. The same function indented with tabs

https://github.com/akinomyoga/ble.sh/assets/34401005/0214826b-2806-4d34-a8ce-0ecaa81014d2

**Comment by akinomyoga** [comment] 2024-01-30 08:45
Thank you for the report! OK, I can reproduce the problem. It's been a long time since I last tested the non-default `bleopt tab_width`, so it might be broken at some point (or was broken from the beginning).

I'll fix it later. The problem doesn't arise with the default `bleopt tab_width=` in my environment, so maybe you can temporarily use `bleopt tab_width=` until I fix it.

**Comment by akinomyoga** [comment] 2024-01-30 19:27
> [...] `tput it`, how do I change that value? I did some searching but none of the methods work.

It's not possible. It's technically possible, but I guess it's not something that you assume. It requires a larger change.

`tput it` just describes the terminal's behavior, so you first need to change the terminal's behavior for tab stops. Then, you can define a new terminfo definition from an existing one, override `it`, register it to the system, and set it to `TERM`.

- For the tab stops, if your terminal supports dynamic setting of tab stops, it would be possible by sending control sequences for TSM <kbd>[MULTIPLE](https://wezfurlong.org/ecma48/06-modes.html#6215-tabulation-stop-mode)</kbd>, <kbd>[TBC](https://vt100.net/docs/vt510-rm/TBC.html)</kbd>, and <kbd>[HTS](https://vt100.net/docs/vt510-rm/HTS.html)</kbd> or by using <kbd>[CTC](https://wezfurlong.org/ecma48/07-control.html#7210-ctc---cursor-tabulation-control)</kbd>. Or maybe your terminal supports GUI configuration for tab stops. Or, if not, you may need to rewrite the source code of the terminal.
- For the terminfo definition, you can dump the current one by `infocmp > myterm.ti`, rewrite the terminal name at the beginning of `myterm.ti`, rewrite or add a value for `it=<integer>`, and register it by using `tic myterm.ti`.

**Comment by dgudim** [comment] 2024-01-30 19:32
Okay, this is a lot more complicated than I thought) Thanks, I guess I'll wait for the fix then

**Comment by akinomyoga** [comment] 2024-02-06 03:12
Sorry for the delay. I have pushed a fix in f9072c409bde436176722ecba2127bf5af9da546. Now you should be able to turn on `bleopt tab_width=4` without problems. Could you update ble.sh and check the behavior?

**Comment by dgudim** [comment] 2024-02-06 07:02
Thank you! It works now

**Comment by akinomyoga** [comment] 2024-02-06 09:22
Thanks for the confirmation!

**Closed by akinomyoga** 2024-02-06 09:22 UTC
Labels: bug
