### ISSUE TITLE
-bash: TMOUT: readonly variable

### ISSUE THREAD

**Issue by farmerbobathan** [akinomyoga/ble.sh#129] opened 2021-07-13 20:21 UTC
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
ble.sh, version 0.4.0-devel3+a860769 (noarch)

I set up ble.sh on a remote linux machine and now the terminal prints `-bash: TMOUT: readonly variable` many times. Ble.sh works well on my local machine.

**Comment by akinomyoga** [comment] 2021-07-14 04:23
I guess some platform setting in your environment has set `TMOUT` as a readonly variable.

**Q1** What is your Linux distribution (e.g., Fedora, CentOS, RHEL, etc.)?

**Q2** What is the result of the following command?

```bash
$ declare -p TMOUT
```

**Q3** Also, does the problem reproduce with ble.sh loaded in a plain Bash? You can test it by the following commands (where `/path/to/ble.sh` should be replaced by the path to ble.sh in your setup).

```bash
$ bash --norc
$ source /path/to/ble.sh
```

----

I found a discussion a similar error message by searching on the internet.
https://www.pclinuxos.com/forum/index.php?topic=133832.0

Maybe I can just discard the error message when ble.sh internally uses `TMOUT`, but that doesn't solve the real issue but just hides it. The problem here is that TMOUT is used for both the timeout of the Bash session and for the timeout of the `read` builtin. If a user sets TMOUT for the auto-logout from the session, every call of `read` is also affected. To protect the behavior of `read` from such user settings, `ble.sh` wants to locally set a value to `TMOUT` for the timeout of `read`. This internal use of TMOUT is temporary, i.e., the value of TMOUT is immediately restored after the call of `read`. I think the profile settings may set a value of TMOUT, but still should not mark TMOUT as *readonly* because otherwise there is no way to use the `read` builtin reliably.

**Comment by farmerbobathan** [comment] 2021-07-14 05:43
Thanks for looking into this!

**Q1**
The remote machine's distro is Scientific Linux 7.9

**Q2**
```
$ declare -p TMOUT
declare -rx TMOUT="259200"
```

**Q3** Hmm, that's interesting. The problem goes away in a plain bash shell. I'm using the exact same `~/{.bashrc,.profile,.bash_profile}` on both my local machine and the remote machine. Running the greps the only relevant result was in `/etc/profile.d/`:
```
$ cat /etc/profile.d/autologout.sh
#!/bin/bash

# Automatically terminate SSH sessions after 3 days (259200 seconds)

if [[ $USER == "root" ]]; then
  return
fi

export TMOUT=259200
readonly TMOUT
```
The remote computer isn't mine so I'm not able to disable readonly on TMOUT. It looks like you are unsetting TMOUT when you use read. If I'm understanding correctly, 3 days should be long enough to work with ble.sh. Maybe a solution could be to check if TMOUT is readonly and give a warning if it is too short?

**Comment by akinomyoga** [comment] 2021-07-15 02:47
OK! Thank you for the detailed information.

> The remote computer isn't mine so I'm not able to disable readonly on TMOUT.

Hm, OK. Maybe that setting is added by the administrator of that specific host? I'll later try to set up Scientific Linux in my VirtualBox to see whether this timeout setting is provided by the distribution or is the specific setting in the system you log in.

> It looks like you are unsetting TMOUT when you use read. If I'm understanding correctly, 3 days should be long enough to work with ble.sh. Maybe a solution could be to check if TMOUT is readonly and give a warning if it is too short while discarding the error message?

Yeah, that could indeed solve the problem, but I'm not sure if that is the right solution. I think one shouldn't make TMOUT readonly because it can break any shell programs loaded in Bash sessions that use `TMOUT`, and also it prevents users from setting up their own TMOUT. Maybe the administrator would like to restrict the use of the computer by making TMOUT readonly, but it is an imperfect restriction because it can be easily bypassed by starting a new non-login Bash session as you have pointed out.

If the setting is defined by the distribution, I think I would try to ask the background of the setting in the mailing list of Scientific Linux, and then decide how we should solve this problem.

**Comment by killermoehre** [comment] 2021-08-03 14:33
In my experience in a corporate environment, `TMOUT` is set read-only to enforce that users don't stay logged in indefinitely. This is due to regulations and requirements.

@farmerbobathan I was able to circumvent this at $customer by checking where the variable was declared read-only. I figured out that the local administrators did a not-so-well job and local script injection was possible (script injection was by design), where the code path defined by the admins was skipped.

**Comment by akinomyoga** [comment] 2021-08-03 16:42
Sorry, for the blank. It took some time, but I actually couldn't set up Scientific Linux in my VirtualBox (somehow the installation requires the internet connection even with the full ISO image (not net install disk), and the internet connection cannot be established even if the network for the VirtualBox host is properly set up. Instead, I found the pre-installed VirtualBox image of Scientific Linux of a slightly older version and confirmed that there is no `readonly TMOUT` settings in Scientific Linux. So I think we can conlude that the readonly TMOUT setting in @farmerbobathan's environment is made by the administrator of that specific host and not the default of Scientific Linux. So I wouldn't report it to Scientific Linux. Actually, Scientific Linux distribution seems to have been dead and no longer mainteined.

> In my experience in a corporate environment, `TMOUT` is set read-only to enforce that users don't stay logged in indefinitely. This is due to regulations and requirements.

Thank you for the comment! Yeah, I could find several pages that describe this technique, but I believe this technique is invented by a not-well-trained user. If one really wants to define the login timeout, one should handle it in the connection layer or something other place. Not only that `readonly TMOUT` can be removed by starting a new non-login Bash session, `readonly TMOUT` doesn't work when the user is opening a terminal application (such as text editor, etc.) inside the terminal. There are many caveats.

Anyway, as there seem to be many hosts using this wrong technique, I should add a workaround for `readnly TMOUT` in ble.sh. I actually have already implemented it in `dev` branch. I'll later push it to `master` branch.

**Comment by akinomyoga** [comment] 2021-08-19 11:36
Sorry for the blank again. I have pushed a workaround in `master` branch 44e6ec1. I also supported `TMOUT` as the session timeout 0e16dbd. @farmerbobathan I'd appreciate it if you could test it in the remote host of Scientific Linux. You can update ble.sh by running ble-update in a ble.sh session:

```bash
$ ble-update
```

Or by running the following command from outside the ble.sh session (please replace `/path/to` with the location of the script file `ble.sh`):

```bash
$ source /path/to/ble.sh --update
```

**Comment by farmerbobathan** [comment] 2021-08-20 17:34
Thank you again. After updating ble.sh I no longer get the readonly variable messages. If are any more specific tests you would like me to do, let me know.

**Comment by akinomyoga** [comment] 2021-08-20 19:37
OK! Thank you for checking. It's fine if no error messages are shown. Thank you again for the report. I close the issue.

**Closed by akinomyoga** 2021-08-20 19:37 UTC
