### ISSUE TITLE
More documentation for flags

### ISSUE THREAD

**Issue by bbyfacekiller** [akinomyoga/ble.sh#152] opened 2021-11-26 07:22 UTC
Hi,

first of all let me say thank you for this awesome readline replacement. It's a joy to use. It killed fish for me.
I think one of the killer features of ble.sh is the documentation for flags when doing completion on utilities. I was wondering if we can get more of it. For awk, sed, wget, etc. Or if there is any way we can contribute?

Thanks a lot for your work!

**Comment by akinomyoga** [comment] 2021-11-26 13:07
Thank you for your comment and the suggestion! I'm busy recently, but I have made a related comment here: https://github.com/akinomyoga/ble.sh/issues/132#issuecomment-908266634. The problem is that `bash-completion` and `ble.sh` both provide some completions for flags, but only the latter provides the description. When `bash-completion` is enabled, it overrides the `ble.sh`'s completion, and thus the flag descriptions are disabled for commands that `bash-completion` covers. I have a plan of integrating both results but do not have enough time to work on it now.

**Comment by akinomyoga** [comment] 2021-12-06 14:15
I actually found that the code of the extraction of supported options from `man` pages for `awk` and `sed` was incomplete. I have improved the extraction of options in commit 6932018. I have also implemented the following idea in commit c1cd666.

> https://github.com/akinomyoga/ble.sh/issues/132#issuecomment-90826663 by @akinomyoga
>
> Maybe I need to think about integrating both results from the external completions and ble.sh built-in option completions.

@bbyfacekiller Can you check if the option completions for `awk` and `sed` now work as expected?

----

The extraction of options from the `man` page of `wget` does not seem to work yet. I'll later check it.

**Comment by akinomyoga** [comment] 2021-12-11 21:49
@bbyfacekiller In commit a79280e, I have also adjusted the man-page extraction for `wget`, `curl`, `mv`, `bc`, `top`, `fish`, and `ping`. Could you test it with the latest commit in `master` branch? You can update `ble.sh` by running the command `ble-update` in a ble.sh session.

**Comment by bbyfacekiller** [comment] 2021-12-14 07:15
Done. Updated. Works fantastic. :P

**Comment by akinomyoga** [comment] 2021-12-15 00:09
Thank you for checking! I close the issue.

**Closed by akinomyoga** 2021-12-15 00:09 UTC
Labels: NYI/NewFeat
