### ISSUE TITLE
Something is prepending and appending a "@" to PS1

### ISSUE THREAD

**Issue by Strykar** [akinomyoga/ble.sh#257] opened 2022-12-02 17:46 UTC
```
[strykar@i-5 ~]$ @echo $PS1
[\u@\h \W]\$

[strykar@i-5 ~]$ @
```
If `PS1=[\u@\h \W]\$` the terminal should look like `[strykar@i-5 ~]$` instead of `[strykar@i-5 ~]$ @`.
If I disable ble.sh, the prompt is prepended with the `@` like `@ [strykar@i-5 ~]$`.

How do I troubleshoot this?

**Comment by akinomyoga** [comment] 2022-12-03 01:22
This is a duplicate of #210. If you would like to modify the question, you can edit the question as

![image](https://user-images.githubusercontent.com/8982192/205415655-3b0dc281-cbd4-439b-9468-b3178a7f908f.png)

**Closed** 2022-12-03 01:22 UTC
Labels: duplicate

**Comment by akinomyoga** [comment] 2022-12-08 19:19
> If `PS1=[\u@\h \W]\$` the terminal should look like `[strykar@i-5 ~]$` instead of `[strykar@i-5 ~]$ @`.
> If I disable ble.sh, the prompt is prepended with the `@` like `@ [strykar@i-5 ~]$`.

FYI, the position of the marker `@` (which is enabled by `set show-mode-in-prompt on` in `.inputrc`) in ble.sh was fixed from the end of the prompt to the beginning in commit 09bb4d3.
