### ISSUE TITLE
Declaring certain exported variables as read only breaks return codes for hooks

### ISSUE THREAD

**Issue by SuperSandro2000** [akinomyoga/ble.sh#186] opened 2022-04-14 15:30 UTC
**ble version**: 0.4.0-devel3+e5d8d00
**Bash version**: 5.1.8(1)-release (x86_64-pc-linux-gnu)

On my KDE Plasma machine I have set ``readonly LC_COLLATE`` because it kept setting ``LC_COLLATE`` to ``en_DE.UTF-8`` which basically no program understands. The root cause of this is that I have English as my display language and German for time and date formats. Today I noticed that my return codes are always 1 even when doing `echo`. After 3 hours it turned out that setting ``LC_COLLATE`` to readonly was the problem. Do you have any idea why? And for the future: How can I turn on some debugging in ble.sh to get more information and errors?

**Comment by akinomyoga** [comment] 2022-04-14 21:41
`ble.sh` uses `LC_COLLATE`, so it doesn't work if it is globally set readonly. In Bash, global readonly variables are considered constant in any context including in the function scope unlike the readonly or constant variables in the other languages. Even the local variables of the same name cannot overwrite the value. Because of this, if any variable is declared readonly in the global context, I cannot ensure that `ble.sh` works correctly when the same variable name is used in ble.sh.

I actually don't recommend declaring any global Bash variables readonly even without ble.sh. Readonly local variables can be used because their behavior is more similar to the other languages. There are some references:

- [bug-bash (thread)](https://lists.gnu.org/archive/html/bug-bash/2019-03/threads.html#00150)
- [bug-bash (thread)](https://lists.gnu.org/archive/html/bug-bash/2020-04/threads.html#00200)
- [BashProgramming - Greg's Wiki](https://mywiki.wooledge.org/BashProgramming?highlight=%28%22readonly%22%20flag,%20or%20an%20%22integer%22%20flag,%20but%20these%20are%20mostly%20useless,%20and%20serious%20scripts%20shouldn%27t%20be%20using%20them%29#Variables)

(though I doubt Greg's idea of "*readonly is for rbash*").

> because it kept setting `LC_COLLATE` to `en_DE.UTF-8` which basically no program understands.

In this sentence, what does no program understand? `LC_COLLATE`, `en_DE.UTF-8`, or the fact that you have set the value? `LC_COLLATE` affects the behavior of `libc`, so every program possibly has a dependency on the variable. Any sorting may be affected (e.g. `sort`, `ls`, `echo *`, etc.). Any regular expression or glob patterns of the form `[a-zA-Z0-9_]` can be affected.

> Do you have any idea why?

`ble.sh` sets `LC_COLLATE` to e.g. test the variable name by the bracket expression of regex and glob patterns by `[a-zA-Z0-9_]`, etc.

> And for the future: How can I turn on some debugging in ble.sh to get more information and errors?

I guess you have `set -x` and `set -v` in your mind, but `ble.sh` currently kills the features of `set -xv` for the case a user wants to debug their command. This is because thousands of lines will be output with these settings being turned on in ble.sh, which would probably be not what the user wants. As for `set -x`, I had once thought about properly setting `BASH_XTRACEFD` up for ble.sh but haven't yet implemented it. As for `set -v`, I currently don't have an idea of how to make it work in `ble.sh`, where `stderr` is also used for certain manipulations.

**Comment by SuperSandro2000** [comment] 2022-04-14 22:50
> In this sentence, what does no program understand? LC_COLLATE, en_DE.UTF-8, or the fact that you have set the value? 

`en_DE.UTF-8`

Do you have an idea how to figure out where the variable gets reset? If I normally start my shell blesh also resets it to `en_DE.UTF-8`  which is super annoying.

> LC_COLLATE affects the behavior of libc, so every program possibly has a dependency on the variable. Any sorting may be affected (e.g. sort, ls, echo *, etc.). Any regular expression or glob patterns of the form [a-zA-Z0-9_] can be affected.

Yeah, I know and `en_DE.UTF-8` is a value which is not really supported.

> I guess you have set -x and set -v in your mind

I was only thinking about `set -x` and yeah, I was searching for something like `BLESH_DEBUG` or `BLESH_VERBOSE`.

Edit: I thound a file which contains the LC_COLLATE setting but it is in ini format... `~/.config/plasma-localerc`

**Comment by akinomyoga** [comment] 2022-04-15 01:22
Ah, OK. I think I now understand the initial report correctly. So the problem is that `en_DE.UTF-8` is actually an invalid locale name, and `LC_COLLATE` is reset to that value somewhere inside `ble.sh`? Hmm, `ble.sh` changes `LC_COLLATE` but only as a local variable, so the value should be recovered when the control returns from the functions. Also, `ble.sh` just sets it to `C` but does not set to any other strings like `en_DE.UTF-8`.

- I'm not sure but maybe some `trap` or `PROMPT_COMMAND` are changing `LC_COLLATE`?

> I was only thinking about `set -x` and yeah, I was searching for something like `BLESH_DEBUG` or `BLESH_VERBOSE`.

OK, now I understand the situation. In this case, for the time being, I think you can just delete the character `x` in [this line](https://github.com/akinomyoga/ble.sh/blob/e5d8d00cf52bb899af0ecab563be12dfc11451ba/ble.pp#L326) and again run `make` (and `make install` if applicable).

**Comment by SuperSandro2000** [comment] 2022-04-15 01:51
Found the culprit https://www.reddit.com/r/archlinux/comments/mqu62u/psa_if_youre_using_kde_plasma_and_cant_understand/

Just deleted `~/.config/plasma-localerc`.

**Comment by akinomyoga** [comment] 2022-05-03 09:55
Let me close this issue as well.

**Closed by akinomyoga** 2022-05-03 09:55 UTC
Labels: External Bug

**Comment by akinomyoga** [comment] 2022-06-10 08:50
> > I guess you have set -x and set -v in your mind
> 
> I was only thinking about `set -x` and yeah, I was searching for something like `BLESH_DEBUG` or `BLESH_VERBOSE`.

FWIW, I have supported `bleopt debug_xtrace=filename` (022d38b). I have also added a section mentioning the global readonly variables (5fb42c2), though it was my misunderstanding that this issue was related to the global readonly variables.

**Comment by SuperSandro2000** [comment] 2022-06-11 11:20
Thanks
