### ISSUE TITLE
Last exit status in PS1 is always 1

### ISSUE THREAD

**Issue by nihilismus** [akinomyoga/ble.sh#136] opened 2021-09-14 01:19 UTC
**ble version**: `0.4.0-devel3+fcf634b`
**Bash version**: `5.1.8(1)-release (x86_64)`

While using `export PS1='$(echo $?) :: '` and with _ble.sh_ enabled I'm getting the next behavior:

```
1 :: ls C:
/usr/bin/ls: cannot access 'C:': No such file or directory
1 :: cd C:
bash: cd: C:: No such file or directory
1 :: true
1 :: echo

1 :: file /
/: directory
1 ::
```

As you can see `$?` is always `1`.

If I disable _ble.sh_ I'm getting the expected behavior:

```
1 :: ble-detach
[ble: detached]
Please run `stty sane' to recover the correct TTY state.
1 :: stty sane;
0 :: ls C:
/usr/bin/ls: cannot access 'C:': No such file or directory
2 :: cd C:
bash: cd: C:: No such file or directory
1 :: true
0 :: echo

0 :: file /
/: directory
0 :: 
```
And if I enable _ble.sh_ once again:

```
0 :: ble-attach 
1 :: false
1 :: true
1 :: file /
/: directory
```

Currently the only way to fix this is to use commit a034c91a90768c640dd5288367461ac36885c12c to install _ble.sh_.

**Comment by akinomyoga** [comment] 2021-09-14 02:02
Ah! Thank you for the report! Also thank you for identifying the commit! There was an oversight In commit 8b5da08 (which is just after the commit you reported). I fixed it 521aff9. Could you confirm the problem is fixed in the latest `master` branch? You can update `ble.sh` by the command `ble-update` in a ble.sh session.

**Comment by nihilismus** [comment] 2021-09-14 02:18
Wow, that was fast ^_^

Thanks a lot, the issue has been fixed:

```
$ echo "$BLE_VERSION"
0.4.0-devel3+521aff9
$ echo "$BASH_VERSION ($MACHTYPE)"
5.1.8(1)-release (x86_64)
$ export PS1='$(echo $?) :: '
0 :: ls /does/not/exist
/usr/bin/ls: cannot access '/does/not/exist': No such file or directory
2 :: true
0 :: false
1 :: true
0 :: 
```

**Comment by akinomyoga** [comment] 2021-09-14 02:24
Thank you for checking! Now I close the issue. Thank you again for the report!

**Closed by akinomyoga** 2021-09-14 02:24 UTC
