### ISSUE TITLE
Completions broken for ugrep 

### ISSUE THREAD

**Issue by dgudim** [akinomyoga/ble.sh#474] opened 2024-08-01 18:52 UTC
```
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu) [EndeavourOS]
ble.sh, version 0.4.0-devel4+bb2dae6e (noarch) [git 2.45.2, GNU Make 4.4.1, GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.14.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
fzf key-bindings, (hash:2da32cbab672fc962b4c56c6a052a6bf47ef2c12, 5618 bytes) (noarch) (integration: on)
fzf completion, (hash:a68dac96ed6e60c7dc412b44705f6a343089146f, 16216 bytes) (noarch) (integration: on)
zoxide, version 0.9.4 (/usr/bin/zoxide)
atuin, version 18.3.0 (/usr/bin/atuin)
locale: LANG=en_US.UTF-8 LC_ADDRESS=en_US.UTF-8 LC_IDENTIFICATION=en_US.UTF-8 LC_MEASUREMENT=C LC_MONETARY=lt_LT.UTF-8 LC_NAME=C LC_NUMERIC=C LC_PAPER=C LC_TELEPHONE=lt_LT.UTF-8 LC_TIME=ru_RU.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, konsole:220380 (1;115;0)
```

Completions for ugrep-indexer (https://github.com/Genivia/ugrep) are broken. This may be an issue on the ugrep side, but still. 
![image](https://github.com/user-attachments/assets/dc26db41-993c-465a-92e5-6dc22e02c1fe)

**Comment by akinomyoga** [comment] 2024-08-01 22:44
These are causing the issue:

- [`completions/bash/compgen.sh:213`](https://github.com/Genivia/ugrep/blob/445f314c6d8dc5dd8a3547576be49d4bb3ad1054/completions/bash/compgen.sh#L200-L213)
- [`completions/bash/ug:195`](https://github.com/Genivia/ugrep/blob/445f314c6d8dc5dd8a3547576be49d4bb3ad1054/completions/bash/ug#L195-L332)
- [`completions/bash/ugrep-indexer:59`](https://github.com/Genivia/ugrep/blob/445f314c6d8dc5dd8a3547576be49d4bb3ad1054/completions/bash/ugrep-indexer#L59-L93)

This is a hack relying on the detailed behavior of plain Bash for multiple ambiguous completions. The `ug` completions use the list of completions to show the help content. But this is merely a hack and not an intended usage of `COMPREPLY`. Even without `ble.sh`, this would be broken by various factors.

- For example, Bash sorts the ordering of completion entries by the collation order of the current locale `LC_COLLATE`. This completion setting seems to assume that `Usage:` comes before the option names, but it's not ensured. For example, if one sets `LANG=C` or `LC_COLLATE=C` or `LC_ALL=C`, 
- Also, if the user uses the bindable readline functions [`menu-complete` and `menu-complete-backward`](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Completion.html), even if the completions are ambiguous, Bash inserts the first item in the command line. The `ug` completion should at least check `COMP_TYPE` to detect the menu completion and avoid this.
- The readline bindable function `insert-completions` (by default bound to `M-*`) is also affected.

I think @genivia-inc should be able to handle this.

**Comment by genivia-inc** [comment] 2024-08-02 01:49
You mean the "usage" part in `_comp_cmd_ugrep_indexer_usage()`?

It's a nice hack to get the help page converted to a completion list. The help page is auto-generated from the ugrep command with compgen.sh for ugrep completions (but not for the ugrep-indexer completions).

Note that `compopt -o nosort` is used when generating `COMPREPLY` for "Usage". I did this because I ran into such problems early on when writing this code. After testing I never saw any problems with it on Debian with the US locale and a foreign locale. Sorting is disabled. So I'm not sure if I can replicate this. Now, there are plenty of online posts about similar problems and some solutions (i.e. `-nosort`) but also issues with specific bash versions and bindings such as `completion-ignore-case` that disable `-nosort`.

**Comment by akinomyoga** [comment] 2024-08-02 03:41
> You mean the "usage" part in `_comp_cmd_ugrep_indexer_usage()`?

Yes.

> Note that `compopt -o nosort` is used when generating `COMPREPLY` for "Usage".

I see. Then, the first problem shouldn't happen.

> but also issues with specific bash versions and bindings such as `completion-ignore-case` that disable `-nosort`.

OK, I tried the behaviors of Bash versions. The option `-o nosort` is introduced in 4.4, but it is disabled by `completion-ignore-case`. This is fixed in 5.0 and later.

@genivia-inc Wouldn't the second and third problems happen with the `ug` completion and `menu-complete`, `menu-complete-forward`, and `insert-completions`? These are unrelated to `-o nosort`.

Also, as reported by @dgudim, this does cause a problem with this project (ble.sh). `ble.sh` wants to process the list of completions, where the expectation is that `COMPREPLY` contains the completions after processing the programmable completions. In the setup of the `ug` completion, the array `COMPREPLY` contains help texts for the empty argument list, which breaks the expectation. How should I handle this?

**Comment by akinomyoga** [comment] 2024-08-02 03:57
The second problem does happen. `menu-complete` inserts `Usage:` in the command line.

![image](https://github.com/user-attachments/assets/ceffb79b-8850-499a-9e59-cafbf85bd309)

The third problem is also present. `insert-completions` (<kbd>M-*</kbd>) inserts all the help text in the command line.

![image](https://github.com/user-attachments/assets/7c7cb99e-d1e8-4c48-80c6-baedc062d00f)

**Comment by genivia-inc** [comment] 2024-08-02 18:08
Oh wow. That's crazy. I have to look into that.

**Comment by akinomyoga** [comment] 2024-08-04 10:14
Maybe you already have a plan on how to solve the issue, but I think `COMP_TYPE` can checked for the issues with plain Bash. The behavior of `COMP_TYPE` is not really explicit in Bash Reference Manual, but the values of `COMP_TYPE` seem to become:

- When bindable function `complete` is called,
  - if this is not the first attempt -> 63
  - otherwise, if show-all-if-ambiguous is enabled -> 33
  - otherwise, if show-all-if-unmodified is enabled -> 64
  - otherwise, 9
- When bindable functions `menu-complete` and `menu-complete-forward` are called -> 37
- When bindable function `insert-completions` is called -> 42

For the present purpose, the hack should be triggered only for `((COMP_TYPE == 33 || COMP_TYPE == 64 || COMP_TYPE == 63))`.

For the issue with ble.sh, `BLE_ATTACHED` can be checked to test whether the completion function is called by `ble.sh`.

**Comment by genivia-inc** [comment] 2024-08-06 21:31
OK. I had some time left over today to look into this for the upcoming release 6.4.

I believe a way forward to handle this all is to change `_comp_cmd_ugrep_usage()` as follows:
```bash
_comp_cmd_ugrep_usage()
{
    local -a usage
    local line i=0
    case $COMP_TYPE in
    33|63|64)
        # generate list of options, concat the first sentence to them
        usage[0]="Usage:"
        while read -r line; do
            # truncate to screen width
            (( ++i ))
            usage[$i]=${line:0:$COLUMNS}
        done < <(_comp_cmd_ugrep_help)
        ;;
    37)
        # generate list of options
        while read -r line; do
            # keep initial option only, remove the rest
            usage[$i]=${line%%[[, ]*}
            (( ++i ))
        done < <(_comp_cmd_ugrep_help)
        ;;
    esac
    COMPREPLY=( "${usage[@]}" )
    compopt -o nosort
}
```

**Comment by akinomyoga** [comment] 2024-08-07 00:00
Thank you, the integration with ble.sh will also be fine with that implementation because ble.sh always sets `COMP_TYPE=9`.

`local -a usage` would better be `local -a usage=()` in case the user sets `shopt -s localvar_inherit` (bash >= 5.0). See this example:

```bash
$ bash -c 'shopt -s localvar_inherit; usage=(1 2 3); f() { local -a usage; usage[0]=Usage; declare -p usage; }; f'
declare -a usage=([0]="Usage" [1]="2" [2]="3")
```

**Comment by genivia-inc** [comment] 2024-08-07 01:09
I've now also worked a bit with ble.sh to see how completions work (or not). It looks alright, but I'm unclear how the Usage works with ble.sh. Sometimes the description text is broken up in two parts with one work next to the option and the rest of the description after a colon. Perhaps ble.sh expects a certain `COMPREPLY` format.

**Comment by akinomyoga** [comment] 2024-08-07 01:50
I'm not sure if I correctly understand what you have tried and what you got, but I guess you tried to include descriptions in `COMPREPLY`, and you see the descriptions included in `COMPREPLY` on the left-hand side of a colon, and the descriptions that ble.sh has independently extracted from the man page of `ug` on the right-hand side of a colon.

> Perhaps ble.sh expects a certain `COMPREPLY` format.

ble.sh expects that `COMPREPLY` doesn't contain any descriptions. `COMPREPLY` is expected to contain just the words to be inserted. Even if you don't include the descriptions in `COMPREPLY`, ble.sh tries to automatically find the corresponding descriptions of options on the man page of `ug`.

If you want to explicitly specify the description instead of letting ble.sh extract from the man page, you can use the internal API `ble/complete/cand/yield` with the word type `mandb` (requires `BLE_VER >= 400`). Instead of storing the option in `COMPREPLY`, you can call `ble/complete/cand/yield` in the loop in the following way:

```bash
ble/complete/cand/yield mandb "$option" "$description"
```

**Comment by genivia-inc** [comment] 2024-08-07 02:18
Ah, that explains. That's easy to handle separately by checking `BLE_ATTACHED` as you suggested. Will give it a spin.

**Comment by akinomyoga** [comment] 2024-08-07 04:44
Sorry, I wrote
> ```shell
> ble/complete/cand/yield mandb "$option" "$description"
> ```

but it should have been

 ```shell
ble/complete/cand/yield mandb "$option" "$_ble_term_FS$_ble_term_FS$_ble_term_FS$description"
```

**Comment by genivia-inc** [comment] 2024-08-07 13:58
After some testing with ble.sh to check `BLE_ATTACHED` in `_comp_cmd_ugrep_usage ()` and take actions to populate `COMPREPLY` with the options only, I came to the conclusion that this does not improve anything. I'd rather let ble.sh generate the list of options. That looks just fine and has no artifacts. So the `_comp_cmd_ugrep_usage()` as was listed above should stay as it is for now.

**Comment by akinomyoga** [comment] 2024-08-07 14:31
> but still has some artifact words of the descriptions included with the option in the list. It is perhaps a ble.sh problem that requires the workaround you describe above with `ble/complete/cand/yield` etc?

The man page parsing is not perfect because there is no established way of describing the command-line options and descriptions in the man page. Different man pages use different formatting for the options and descriptions. ble.sh uses a heuristic way of extracting the option and the description.

For example, if the man page contains something like `-o xxx yyy zzz`, it is generally impossible to robustly determine whether `xxx` is an option argument or the first word of the description. `xxx` may be the option argument in the man pages of some commands, while it may be the first word of the description in the man pages of some other commands. `ble.sh` requires that at least three spaces are placed between the option and the first word of the description.

> Basically, ble.sh thinks that long options always have an argument so it takes the first word from the description as the argument.

Maybe that is related to the man page format in your environment. In my system (Fedora 39), ble.sh correctly extracts the options and the descriptions:

![image](https://github.com/user-attachments/assets/58205272-10f7-4890-84d2-80d12220d1b2)

ble.sh parses the man page source. The section listing the options in the man page source of `ug` looks like this in my system:

```
The following options are available:
.TP
\fB\-A\fR \fINUM\fR, \fB\-\-after\-context\fR=\fINUM\fR
Output NUM lines of trailing context after matching lines.  Places
a \fB\-\-group\-separator\fR between contiguous groups of matches.  If \fB\-o\fR is
specified, output the match with context to fit NUM columns after
the match or shortens the match.  See also options \fB\-B\fR, \fB\-C\fR and \fB\-y\fR.
.TP
\fB\-a\fR, \fB\-\-text\fR
Process a binary file as if it were text.  This is equivalent to
the \fB\-\-binary\-files\fR=text option.  This option might output binary
garbage to the terminal, which can have problematic consequences if
the terminal driver interprets some of it as commands.
.TP
\fB\-\-and\fR [\fB\-e\fR] PATTERN ... \fB\-e\fR \fIPATTERN\fR
Specify additional patterns to match.  Patterns must be specified
with \fB\-e\fR.  Each \fB\-e\fR \fIPATTERN\fR following this option is considered an
alternative pattern to match, i.e. each \fB\-e\fR is interpreted as an OR
pattern.  For example, \fB\-e\fR \fIA\fR \fB\-e\fR \fIB\fR \fB\-\-and\fR \fB\-e\fR \fIC\fR \fB\-e\fR \fID\fR matches li
nes with
(`A' or `B') and (`C' or `D').  Note that multiple \fB\-e\fR \fIPATTERN\fR are
alternations that bind more tightly together than \fB\-\-and\fR.  Option
\fB\-\-stats\fR displays the search patterns applied.  See also options
\fB\-\-not\fR, \fB\-\-andnot\fR, \fB\-\-bool\fR, \fB\-\-files\fR and \fB\-\-lines\fR.
```

Although ble.sh doesn't parse the result rendered by groff/nroff/troff, the corresponding rendered result looks like

```
       -A NUM, --after-context=NUM
              Output NUM lines of trailing context after matching lines.  Places a  --group-separator  between  con‐
              tiguous groups of matches.  If -o is specified, output the match with context to fit NUM columns after
              the match or shortens the match.  See also options -B, -C and -y.

       -a, --text
              Process a binary file as if it were text.  This is equivalent to the --binary-files=text option.  This
              option  might  output  binary  garbage to the terminal, which can have problematic consequences if the
              terminal driver interprets some of it as commands.

       --and [-e] PATTERN ... -e PATTERN
              Specify additional patterns to match.  Patterns must be specified with -e.  Each -e PATTERN  following
              this  option  is considered an alternative pattern to match, i.e. each -e is interpreted as an OR pat‐
              tern.  For example, -e A -e B --and -e C -e D matches lines with (`A' or `B') and (`C' or `D').   Note
              that  multiple -e PATTERN are alternations that bind more tightly together than --and.  Option --stats
              displays the search patterns applied.  See also options --not, --andnot, --bool, --files and --lines.

       --andnot [-e] PATTERN
              Combines --and --not.  See also options --and, --not and --bool.

       -B NUM, --before-context=NUM
              Output NUM lines of leading context before matching lines.  Places a  --group-separator  between  con‐
              tiguous  groups  of matches.  If -o is specified, output the match with context to fit NUM columns be‐
```

**Comment by genivia-inc** [comment] 2024-08-07 14:49
I'm using ble.sh on an RPi by building it from source. I don't see a `ble/complete/mandb` location in this build.

**Comment by akinomyoga** [comment] 2024-08-07 14:52
`ble/complete/mandb` is not a location. It's a part of *the shell function name*:

```bash
$ type ble/complete/mandb/search-file
ble/complete/mandb/search-file is a function
ble/complete/mandb/search-file ()
{
    local command=$1;
    local path;
    ble/complete/mandb/search-file/.extract-path "$command";
    ble/complete/mandb/search-file/.check "$path" && return 0;
    ble/string#split ret : "$MANPATH";
    ((${#ret[@]})) || ret=('');
    local -a manpath=();
    for path in "${ret[@]}";
    do
        if [[ -n $path ]]; then
            ble/array#push manpath "$path";
        else
            ble/complete/mandb/initialize-manpath;
            ble/array#push manpath "${_ble_complete_mandb_default_manpath[@]}";
        fi;
    done;
    local path;
    for path in "${manpath[@]}";
    do
        [[ -d $path ]] || continue;
        ble/complete/mandb/search-file/.check "$path/man1/$command.1" && return 0;
        ble/complete/mandb/search-file/.check "$path/man1/$command.8" && return 0;
        if ble/is-function ble/bin/gzip; then
            ble/complete/mandb/search-file/.check "$path/man1/$command.1.gz" && return 0;
            ble/complete/mandb/search-file/.check "$path/man1/$command.8.gz" && return 0;
        fi;
        if ble/is-function ble/bin/bzcat; then
            ble/complete/mandb/search-file/.check "$path/man1/$command.1.bz" && return 0;
            ble/complete/mandb/search-file/.check "$path/man1/$command.1.bz2" && return 0;
            ble/complete/mandb/search-file/.check "$path/man1/$command.8.bz" && return 0;
            ble/complete/mandb/search-file/.check "$path/man1/$command.8.bz2" && return 0;
        fi;
        if ble/is-function ble/bin/xzcat; then
            ble/complete/mandb/search-file/.check "$path/man1/$command.1.xz" && return 0;
            ble/complete/mandb/search-file/.check "$path/man1/$command.8.xz" && return 0;
        fi;
        if ble/is-function ble/bin/lzcat; then
            ble/complete/mandb/search-file/.check "$path/man1/$command.1.lzma" && return 0;
            ble/complete/mandb/search-file/.check "$path/man1/$command.8.lzma" && return 0;
        fi;
    done;
    return 1
}
```

It's defined when `ble.sh` is loaded in the session. Can you just run the command in a ble.sh session?

**Comment by genivia-inc** [comment] 2024-08-07 14:57
Ah, the path seps threw me off track. The output is:
```
0, /usr/local/share/man/man1/ugrep.1
```
That ugrep.1 man page is the latests v6.3 that I installed most recently.

**Comment by genivia-inc** [comment] 2024-08-07 15:07
So on the RPI I am using a Dutch locale. I use this to test if my code runs fine with non-US locale, always a good thing to try. There may be a problem with ble.sh and this locale, because when I switch to the english/US locale and UTF-8, then the results no longer show the "long options with a word from the description" artifacts.

**Comment by akinomyoga** [comment] 2024-08-07 15:13
Ah, OK. I think the version of `ug` in my system (Fedora 39) is just too old and the completion setting is not the same. In my system,

```bash
$ ug --version
ugrep 3.12.7 x86_64-redhat-linux-gnu +avx2 +pcre2jit +zlib +bzip2 +lzma +lz4 +zstd
License BSD-3-Clause: <https://opensource.org/licenses/BSD-3-Clause>
Written by Robert van Engelen and others: <https://github.com/Genivia/ugrep>
$ complete -p ug
complete -F _comp_complete_minimal ug
$ complete -p ugrep
complete -F _comp_complete_minimal ugrep
```

So in my system, no dedicated completion settings for `ug` and `ugrep` are installed. 

In the Bash completion settings for `ug` in the latest version, [bash-completion's `_parse_help` seems to be called](https://github.com/Genivia/ugrep/blob/d12bacd6713948d726e8be99cde1e7bcc22e08b6/completions/bash/ug#L172) to generate the long option names by feeding the output of `_comp_cmd_ugrep_help`. ble.sh hooks into bash-completion's `_parse_help` and processes the help text that `_parse_help` sees. This might be interfering.

Hmm, I tried the latest version of the Bash completion setting of `ug`. The problem still doesn't seem to reproduce because the options and descriptions extracted from the man page have a higher priority than the ones extracted through `_parse_help`.

> when I switch to the english/US locale and UTF-8, then the results no longer show the "long options with a word from the description" artifacts.

Ah, OK. Maybe that is the cache issue. Could you clear the cache of ble.sh (`rm -rf "$_ble_base_cache"`) and restart ble.sh?

**Comment by genivia-inc** [comment] 2024-08-07 18:11
Yeah, looks like emptying the cache worked! Checked with both locales and for `ug` and `ugrep`. This is with the `_comp_cmd_ugrep_usage()` that I had posted earlier. I'll update ugrep to v6.4 later today or tomorrow with this version.

**Comment by genivia-inc** [comment] 2024-08-08 00:42
This issue can be closed as resolved?

**Comment by akinomyoga** [comment] 2024-08-08 05:01
OK! Thank you! @dgudim If you still have the issue, you can reopen this issue.

**Closed by akinomyoga** 2024-08-08 05:01 UTC
