### ISSUE TITLE
Disabling history modifiers expansion is not working anymore

### ISSUE THREAD

**Issue by getchup** [akinomyoga/ble.sh#513] opened 2024-10-02 15:57 UTC
I've been using `bleopt edit_magic_expand =` to disable expansion of history modifiers like `!!`, `!:0`, etc. but this setting doesn't seem to be working anymore, as modifiers get expanded anyways.
```

GNU bash, version 5.2.37(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel4+32f290df (noarch) [git 2.46.2, GNU Make 4.4.1, GNU Awk 5.3.1, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
locale: LANG=en_US.UTF-8
terminal: TERM=xterm-kitty wcwidth=15.0-west/16.0-2+ri, kitty:0 (1;4000;36)
options: +cdspell +inherit_errexit
```

**Comment by akinomyoga** [comment] 2024-10-02 18:20
It works as expected as far as I check the behavior in my environment. With `bleopt edit_magic_expand=`, the magic expansion (i.e., the expansion caused by pressing <kbd>SP</kbd>) is disabled as expected in my environment.

> I've been using `bleopt edit_magic_expand =` to disable expansion of history modifiers like `!!`, `!:0`, etc. as modifiers get expanded anyways.

What do you mean by "expansion of history modifiers"? If you are talking about "*the history expansion performed when the command is executed*" instead of "*the history expansion performed by the magic expansion*", `bleopt edit_magic_expand` is not the option for that. The option to disable the history expansion is `set +H`.

**Comment by getchup** [comment] 2024-10-05 13:31
What I meant to say is that I expect a history modifier to stay like that on the line when I press enter and not be replaced with the actual command it replaces. For example if I run a command `echo hello` and then type the modifier `!!` on the next line, the `!!` gets replaced and displayed as `echo hello` instead of being kept as `!!`.

I'm talking about how the history modifiers on the readline are displayed after being executed.

**Comment by akinomyoga** [comment] 2024-10-05 13:48
In that case, you can remove `verify-syntax` from [`bleopt edit_magic_accept`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#user-content-bleopt-edit_magic_accept). If you haven't added any other options to `bleopt edit_magic_accept`, you can simply set `bleopt edit_magic_accept=`.

The option `verify-syntax` was introduced in commit ac84c153a5038814960475b0721f6ac6fad64bf2 (for #138). It performs the history expansion explicitly to check the syntax after the history expansion.

**Comment by getchup** [comment] 2024-10-05 13:57
Thank you! This is what I've been looking for.

**Comment by akinomyoga** [comment] 2024-10-06 21:21
Thank you. Can I close the issue?

**Comment by getchup** [comment] 2024-10-07 05:39
Sure.

**Comment by akinomyoga** [comment] 2024-10-07 05:54
Thank you!

**Closed by akinomyoga** 2024-10-07 05:54 UTC
