### ISSUE TITLE
Bash/Terminal Emulator crashes if you type something that's supposed to fetch auto-completion suggestions but you press backspace to delete what you just typed before the auto-completion suggestions could finish processing

### ISSUE THREAD

**Issue by 103sbavert** [akinomyoga/ble.sh#471] opened 2024-07-27 15:06 UTC
# Version information
```
GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu) [Arch Linux]
ble.sh, version 0.4.0-devel4+fcbf1ed0 (noarch) [git 2.45.2, GNU Make 4.4.1, GNU Awk 5.3.0, API 4.0, PMA Avon 8-g1, (GNU MPFR 4.2.1, GNU MP 6.3.0)]
bash-completion, version 2.14.0 (hash:480ffcc6a751e55621ec526eb5dea7a0d86d9e72, 17877 bytes) (noarch)
locale: LANG=en_US.UTF-8 LC_ADDRESS=en_IN.UTF-8 LC_MEASUREMENT=en_IN.UTF-8 LC_MONETARY=en_IN.UTF-8 LC_NUMERIC=en_IN.UTF-8 LC_PAPER=en_IN.UTF-8 LC_TELEPHONE=en_IN.UTF-8 LC_TIME=en_IN.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-west/15.1-2+ri, unknown:- (61;7603;1)
```
# Ble.sh crashes if you press try to erase your input before auto-complete suggestions could finish processing after the input
Suppose you're using yay (the pacman wrapper and the AUR helper). If you type, say, `yay -S ip` and instantly press backspace (maybe you made a mistake with the typing or something) and the auto-complete suggestions haven't loaded yet, ble.sh, and bash, and the terminal emulator, end up crashing.

# Video demonstrating the error
[Screen recording](https://github.com/user-attachments/assets/043ee445-3893-4dd7-afef-ccbee5868f25)

**Comment by akinomyoga** [comment] 2024-07-27 15:54
Thanks for the report, but I've never experienced the crash in my environment.

Just to confirm, does it only happen with the `yay` completion? Or does it happen with any commands with slow completion generation?

**Comment by 103sbavert** [comment] 2024-07-27 15:56
Happens with something like `cat` as well if, say, you're in a folder with 1000s of files.

**Comment by 103sbavert** [comment] 2024-07-27 16:23
[bleshlog.txt](https://github.com/user-attachments/files/16400859/bleshlog.txt)

**Comment by akinomyoga** [comment] 2024-07-27 16:42
The number of invocation of `sudo -v` in `command_not_found_handle` seem to exponentially increasing. Do you have an alias named `sudo`? What is the result of the following command?

```bash
$ alias
```

**Comment by akinomyoga** [comment] 2024-07-27 16:59
Does putting the following function in your `~/.blerc` fix the issue?

```bash
function ble/function#evaldef {
  local has_extglob=
  shopt -q extglob && has_extglob=1
  local has_expand_aliases=
  shopt -q expand_aliases && has_expand_aliases=1
  shopt -s extglob
  shopt -u expand_aliases
  builtin eval -- "$1"; local ext=$?
  [[ $has_extglob ]] || shopt -u extglob
  [[ $has_expand_aliases ]] && shopt -s expand_aliases
  return "$ext"
}
```

**Comment by 103sbavert** [comment] 2024-07-27 18:45
I'll try tomorrow, its late right now.

**Comment by 103sbavert** [comment] 2024-07-28 05:00
This may or may not be helpful but the problem doesn't occur in blesh stable

**Comment by akinomyoga** [comment] 2024-07-28 06:18
There are large differences between 0.3.4 and 0.4, so I'm afraid to say that it doesn't help to fix the problem in 0.4. Could you check the replies https://github.com/akinomyoga/ble.sh/issues/471#issuecomment-2254196504 and https://github.com/akinomyoga/ble.sh/issues/471#issuecomment-2254200185. Have you already tried them? What are the results?

**Comment by 103sbavert** [comment] 2024-07-28 11:52
```
$ alias
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias diff='diff --color=auto'
alias dir='dir --color=auto'
alias droid='sh /home/sbeve72/.local/bin/droid'
alias edit='micro'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias ip='ip -color=auto'
alias kernel-name='uname -r'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias python='python3'
alias start-cam='scrcpy --no-audio --video-source=camera --camera-facing=front --orientation=flip0 --camera-size=1920x1080 --v4l2-sink=/dev/video0'
alias sudo='sudo -v; sudo '
alias typeof='xdg-mime query filetype'
alias vdir='vdir --color=auto'
alias yay-autoinstall='yay --needed --quiet --cleanafter --removemake --noconfirm -S --overwrite="*"'
alias yay-autoupdate='yay --noconfirm --removemake --needed --quiet --cleanafter -Syyu --overwrite="*"'
alias yay-clear='yay -Qqd | yay -Rsu -'
alias yay-install='yay --needed --quiet --cleanafter --removemake -S'
alias yay-remove='yay -Rcns'
```



Trying the other thing now

**Comment by 103sbavert** [comment] 2024-07-28 11:56
Yep, the solution in https://github.com/akinomyoga/ble.sh/issues/471#issuecomment-2254200185 wokrs just fine. No longer lag

**Comment by 103sbavert** [comment] 2024-07-28 12:01
Removing the sudo alias also works around the issue apparently

**Comment by akinomyoga** [comment] 2024-07-28 14:38
OK, thank you for checking the behavior. I'll apply the fix in the next push to the `master` branch.

**Comment by akinomyoga** [comment] 2024-07-29 03:11
I pushed a fix 51e762fe1c82e3ecb02940462164860f2765cb32 in the `master` branch. Now I think the problem doesn't happen (without the tentative workaround https://github.com/akinomyoga/ble.sh/issues/471#issuecomment-2254200185 and without removing your `sudo` alias). Could you update `ble.sh` by running `ble-update` and check the behavior?

**Comment by 103sbavert** [comment] 2024-07-29 06:46
Thank you, I'll check it out in the evening for me (IST).

**Comment by 103sbavert** [comment] 2024-07-29 07:56
I am using the AUR to run blesh on my pc, should i use ble-update?

**Comment by akinomyoga** [comment] 2024-07-29 10:08
Commit 51e762fe1c82e3ecb02940462164860f2765cb32 seems to have caused a regression. I pushed a follow-up fix bb2dae6e6bdc15cb853e463021268087b45c54b9 in the `master` branch. Even if you've already updated `ble.sh`, could you update `ble.sh` again?

**Comment by 103sbavert** [comment] 2024-07-29 17:50
There's no update in the AUR for the two latest commits

**Comment by 103sbavert** [comment] 2024-07-29 17:52
Nvm i got it, the issue seems to be resolved now

**Comment by akinomyoga** [comment] 2024-07-29 21:53
The AUR package `blesh-git` is a `*-git` package, i.e., it always picks up the latest commit from the git repository. If you reinstall the `blesh-git` package, it should overwrite the existing installation with the latest version.

Thank you for confirming that the issue is fixed.

**Closed by akinomyoga** 2024-07-29 21:53 UTC
Labels: compatibility
