### ISSUE TITLE
ble-reload triggers -bash: local: BASHPID: readonly variable

### ISSUE THREAD

**Issue by Knusper** [akinomyoga/ble.sh#472] opened 2024-07-29 17:20 UTC
```
-> ble/widget/display-shell-version
GNU bash, version 4.4.20(1)-release (x86_64-redhat-linux-gnu) [Red Hat Enterprise Linux 8.6 (Ootpa)]
ble.sh, version 0.4.0-devel4+bb2dae6 (noarch) [git 2.31.1, GNU Make 4.2.1, GNU Awk 4.2.1, API: 2.0 (GNU MPFR 3.1.6-p2, GNU MP 6.1.2)]
bash-completion, version 2.7 (hash:d3d318284d3f9a575bd400fd38c8729e03b2fb16, 71791 bytes) (noarch)
locale: LANG=en_GB.utf8
terminal: TERM=xterm-256color wcwidth=14.0-west/15.1-2+ri, konsole:30000 (0;115;0)
```

When I run `ble-reload` I get `-bash: local: BASHPID: readonly variable` ... With newer versions of bash (>5) I don't see this error.

(Triggered by update ` fcbf1ed..bb2dae6`)

**Comment by akinomyoga** [comment] 2024-07-29 17:43
Thanks for the report. This is a known bug I committed with commit 51e762f. The issue caused by the same bug was reported in https://github.com/akinomyoga/ble.sh/issues/470#issuecomment-2255357001 and was fixed in commit bb2dae6. The buggy version 51e762f was on the head of the `master` branch for about seven hours (2024-07-29 03:09...10:01 UTC). Users who've updated `ble.sh` during this period would be affected.

I think it should have been triggered the update `51e762f..bb2dae6`. Commit bb2dae6 was the commit to fix the problem, so the problem will not happen again in the next updates.

**Comment by Knusper** [comment] 2024-07-30 05:45
Thanks!

**Comment by Knusper** [comment] 2024-07-30 11:47
Sorry - I must have misunderstood something.  I use `bb2dae6`, and I get these errors.

**Comment by akinomyoga** [comment] 2024-07-30 12:07
What do you mean? I think the problem arises when you reload bb2dae6 in a session where 51e762f is activated. This was fixed. Do you still see the error even when you reload bb2dae6 in a session where bb2dae6 is activated?

**Comment by Knusper** [comment] 2024-07-30 15:39
> Or do you still see the error even when you reload https://github.com/akinomyoga/ble.sh/commit/bb2dae6e6bdc15cb853e463021268087b45c54b9 in a session where https://github.com/akinomyoga/ble.sh/commit/bb2dae6e6bdc15cb853e463021268087b45c54b9 is activated?

Yes.  `ble-reload` in a running session triggers the errors, not only the update.  After the reload nothing works as expected anymore....  E.g. I get also errors like `-bash: _completion_loader -D: command not found`, when trying to tab-complete (this is also on bash v.5).

**Comment by akinomyoga** [comment] 2024-07-30 22:05
OK, there was another control path where `_ble_bash` was lost. I fixed it in commit a9b962d2. Could you check if it fixes the problem?

> E.g. I get also errors like `-bash: _completion_loader -D: command not found`,

I feel this is a separate issue. Could you again check this behavior in the latest commit?

**Comment by Knusper** [comment] 2024-07-31 07:24
> OK, there was another control path where `_ble_bash` was lost. I fixed it in commit [a9b962d](https://github.com/akinomyoga/ble.sh/commit/a9b962d29c5015dde1c98c81dad9c81798b30661). Could you check if it fixes the problem?
> 

Yes, now I don't get this error after doing `ble-reload`.  

> > E.g. I get also errors like `-bash: _completion_loader -D: command not found`,
> 
> I feel this is a separate issue. Could you again check this behavior in the latest commit?

This error only appeared after doing `ble-reload` - now it also not reproducible anymore.

I'm closing for good.  Thanks for your quick response!

**Comment by akinomyoga** [comment] 2024-07-31 08:35
> > I feel this is a separate issue. Could you again check this behavior in the latest commit?
> 
> This error only appeared after doing `ble-reload` - now it also not reproducible anymore.

OK. Thank you for checking the behavior.

**Comment by akinomyoga** [comment] 2024-07-31 08:36
Thank you! and sorry for initially assuming that the problem was already fixed.

**Closed by akinomyoga** 2024-07-31 08:36 UTC
Labels: duplicate
