### ISSUE TITLE
Window resize may duplicate written lines in terminal

### ISSUE THREAD

**Issue by EmilySeville7cfg** [akinomyoga/ble.sh#154] opened 2021-12-02 10:28 UTC
**ble version**: 0.4.0-devel3+82f74f0
**Bash version**: 5.0.17(1)-release (x86_64-pc-linux-gnu)
**Terminal version**: GNOME Terminal 3.36.2
**OS version**: Linux Mint 20.2 Cinnamon

![image](https://user-images.githubusercontent.com/42812113/144404653-586fdfdc-cdc6-455d-b381-37fe2c168f38.png)

**Comment by akinomyoga** [comment] 2021-12-02 10:45
This is a duplicate of #142. This is actually an intended behavior whose reasoning is explained in #142. You can configure the behavior by the option [`bleopt canvas_winch_action`](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A72-Graphics#user-content-bleopt-canvas_winch_action):

```bash
# blerc
bleopt canvas_winch_action=redraw-prev
```

I'm now thinking of improving the behavior of the current default, but I think I'll not soon improve it as the priority is relatively lower than other planned improvements.

**Closed** 2021-12-02 11:53 UTC
Labels: duplicate, question, NYI/NewFeat
