### ISSUE TITLE
If I use history substring search with empty string and press up, how do I make it so I only need to press Enter once?

### ISSUE THREAD

**Issue by mcarans** [akinomyoga/ble.sh#398] opened 2024-02-01 22:26 UTC
I have history substring search from bash-it. When I press up arrow, I get the nsearch and I have to press Enter twice to run the command. I understand from [here](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A74-Editing#410-non-incremental-search-nsearch) that this behaviour can be changed. I don't know where to change it. Please can you advise.

**Comment by akinomyoga** [comment] 2024-02-01 23:15
You can read https://github.com/akinomyoga/ble.sh/issues/101#issuecomment-828541531.

> I have history substring search from bash-it.

Are you talking about this?

- [`bash-it/plugins/available/history-substring-search.plugin.bash` at d985e4c9 · Bash-it/bash-it](https://github.com/Bash-it/bash-it/blob/d985e4c96b1eb4e7374b3ab53eea3513fc9f50ce/plugins/available/history-substring-search.plugin.bash)

Then, you can instead have the following settings:

```bash
ble-bind -f up 'history-substring-search-backward immediate-accept'
ble-bind -f down 'history-substring-search-forward immediate-accept'
```

**Comment by akinomyoga** [comment] 2024-02-02 01:24
> Both of those seem to do what I want, so I was wondering what is the difference between them?

With the latter, the history search doesn't start with the empty command line. When the command line is empty (or the cursor is at the beginning of the command line), it moves to the previous history entry just the same as the default binding to <kbd>up</kbd>.

To talk about the superficial behavioral difference, with the former, the command is always executed by a single <kbd>Enter</kbd>. With the latter, the command is executed by a single <kbd>Enter</kbd> only with the empty command line.

> Neither file exists at the moment.

You need to create one. Either one is fine. ble.sh doesn't try to change the content of the user's data directory.

**Comment by mcarans** [comment] 2024-02-02 01:34
Thank you, that's helpful! Sorry if this is a dumb question, but why wouldn't I always want it to be a single `ENTER` (ie. immediate-accept) or to put it another way, what can I do between the two `ENTER` clicks in the non-empty case?

**Comment by akinomyoga** [comment] 2024-02-02 02:14
> why wouldn't I always want it to be a single `ENTER` (ie. immediate-accept) or to put it another way, what can I do between the two `ENTER` keypresses in the non-empty case?

So that one can edit the command found in the history. You can continue to edit the command line after pressing the first <kbd>Enter</kbd>. In particular, one can use isearch (<kbd>C-r</kbd>/<kbd>C-s</kbd>) and cursor movements (<kbd>up</kbd>/<kbd>down</kbd>) only after the first <kbd>Enter</kbd>.

But maybe it's not so useful in your case because you override <kbd>up</kbd> and <kbd>down</kbd> by nsearch. By overriding <kbd>up</kbd> and <kbd>down</kbd>, you cannot move between lines in the multiline mode.  Actually, nsearch is bound to PageUp and PageDown by default, with which <kbd>up</kbd> and <kbd>down</kbd> after pressing the first <kbd>Enter</kbd> are still useful.

I also wanted to make the behavior consistent with isearch (incremental search) called by <kbd>C-r</kbd> and <kbd>C-s</kbd>, and the isearch behavior is modified to be consistent with the original implementation of Emacs. It's a tiny difference in how <kbd>Enter</kbd> behaves, but the tiny difference between the command line and the editor would be troublesome because it induces mistakes. It is a problem, especially for the command execution that can be destructive.

Also, it would be good to put a pose before running the command quickly picked up. If you are sure that the picked command is correct, you can press <kbd>Ctrl+Enter</kbd> to immediately accept the command. To use <kbd>Ctrl+Enter</kbd> (<kbd>C-RET</kbd>), please refer to *[konsole - Manual A2](https://github.com/akinomyoga/ble.sh/wiki/Manual-A2-Terminal-Settings#konsole)* for the key configuration in Konsole.

**Comment by mcarans** [comment] 2024-02-02 02:38
Thanks for the explanation. I'm not sure what I'm doing wrong, but I can't seem to make the change permanent. I made a file .blerc with:
```
ble-bind -f up 'history-substring-search-backward immediate-accept'
ble-bind -f down 'history-substring-search-forward immediate-accept'
```

At the top of my .bashrc I put:
```
source "$HOME/.local/share/blesh/ble.sh" --rcfile "$HOME/.blerc"
```

At the bottom, I put:
```
ble-attach
```

When I open Konsole, the behaviour is as if there were no .blerc file. What am I missing?

**Comment by akinomyoga** [comment] 2024-02-02 03:23
One possibility is that those bindings are applied to a different keymap. Do you use the vi editing mode?

### If you use the vi editing mode

`ble-bind` without specifying the keymap applies to *the currently selected keymap*, so if you put the settings of `ble-bind` before calling `set -o vi`, those bindings are defined in the emacs keymap.

There are three options that I can come up with immediately. One is to enable the vi editing mode before calling `ble-bind`.

```bash
# blerc

set -o vi
ble-bind -f up 'history-substring-search-backward immediate-accept'
ble-bind -f down 'history-substring-search-forward immediate-accept'
```

Another option is to explicitly specify the keymap:

```bash
# blerc

ble-bind -m vi_imap -f up 'history-substring-search-backward immediate-accept'
ble-bind -m vi_imap -f down 'history-substring-search-forward immediate-accept'
```

The other is to define the binding in the startup hook of the vi editing mode as described at the beginning of [§6.3](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A76-Vim-Mode#user-content-sec-vim-mode-settings):

```bash
# blerc

function my/vim-load-hook {
  ble-bind -f up 'history-substring-search-backward immediate-accept'
  ble-bind -f down 'history-substring-search-forward immediate-accept'
}
blehook/eval-after-load keymap_vi my/vim-load-hook
```

**Comment by mcarans** [comment] 2024-02-02 03:36
I haven't to my knowledge set up vi editing. If I put the lines at the end of my .bashrc, they work:
```
...
ble-attach
ble-bind -f up 'history-substring-search-backward immediate-accept'
ble-bind -f down 'history-substring-search-forward immediate-accept'
```

It is as if the .blerc and .config/blesh/init.sh are completely ignored.

**Comment by akinomyoga** [comment] 2024-02-02 03:47
Hmm, I don't have an idea for now. In my environment it works with the following setup:

```bash
# bashrc
source out/ble.sh --rcfile gh398.blerc --attach=none
ble-attach
```

```bash
# gh398.blerc
ble-bind -f up 'history-substring-search-backward immediate-accept'
ble-bind -f down 'history-substring-search-backward immediate-accept'
```

**Comment by mcarans** [comment] 2024-02-02 03:49
Is there any way to get the .blerc file to be loaded in the `ble-attach` call rather than in the `source ~/.local/share/blesh/ble.sh --noattach` call?

**Comment by akinomyoga** [comment] 2024-02-02 03:50
> EDIT 2: I think I worked out the problem. Sourcing ble.sh at the top happens before sourcing bash-it and so the key bindings in .blerc are loaded before bash-it is set up. The .blerc needs to be loaded after sourcing bash-it somehow.
> 
> ie. this works:

Do you still have Bash-it's `history-substring-search` plugin enabled? Then, this is understandable because those `ble-bind` settings are overwritten by the `history-substring-search` plugin. You need to turn off Bash-it's `history-substring-search` plugin by running

```bash
$ bash-it disable plugin history-substring-search
```

**Comment by akinomyoga** [comment] 2024-02-02 03:54
> Is there any way to get the .blerc file to be loaded in the `ble-attach` call rather than in the `source ~/.local/share/blesh/ble.sh --noattach` call?

No. By design, the users can call `ble-attach` and `ble-detach` multiple times anytime later, so it is strange to run initialization codes in `ble-attach`, which can be called multiple times at an arbitrary timing.

**Comment by mcarans** [comment] 2024-02-02 03:56
Ah brilliant, that's it! I misunderstood - I had thought that ble.sh used bash-it's history substring search. Thanks for all your help.

**Comment by akinomyoga** [comment] 2024-02-02 19:07
Let me close the issue as you seem to have solved the problem. If you haven't been satisfied, please reopen it. Thank you.

**Closed by akinomyoga** 2024-02-02 19:07 UTC
Labels: question
