### ISSUE TITLE
Toggle mode

### ISSUE THREAD

**Issue by E3D3** [akinomyoga/ble.sh#244] opened 2022-10-23 15:45 UTC
I noticed that I can switch from emacs mode to vim mode, and vice versa, with the following commands _IN_ `ble.sh`/the terminal
```
ble-bind -m emacs   -f 'M-e v' 'vi-editing-mode'
ble-bind -m vi_imap -f 'M-e e' 'emacs-editing-mode'
```
But adding this to _blerc_ doesn't work. Then `ble.sh` gives the message that these keybindings are not recognized.
How can I add this key bindings to blerc ?
[I have `ble.sh` version 0.4.0-nightly+a144ffa (noarch)]

**Comment by akinomyoga** [comment] 2022-10-24 05:28
Thanks for the report! It doesn't seem to reproduce in my environment, i.e., with the above settings in `~/.blerc` seem to work as expected.

Where have you put your *blerc*? It needs to be at `~/.blerc` or `~/.config/blesh/init.sh` (`$XDG_CONFIG_HOME/blesh/init.sh`), or you need to specify the location by the option `--rcfile <your blerc file>` to `source .../ble.sh`.

**Comment by E3D3** [comment] 2022-10-24 12:33
I have a first line in my .bashrc
`[[ $- == *i* ]] && source /home/e3d3/.e3progs/ble-nightly-20221001+a144ffa/ble.sh --noattach --rcfile /home/e3d3/.e3config/ble.sh/ble--e3config`
and as last line:
`[[ ${BLE_VERSION-} ]] && ble-attach`

**Comment by akinomyoga** [comment] 2022-10-24 18:42
Thank you for the information. Then, I currently don't have an idea what is going on. I think I need more information.

- **Q2**: What is the result of pressing <kbd>C-x C-v</kbd> in a ble.sh session? (Or, what is your operating system, Bash version, and terminal version?) [ This information is needed for the trial to reproduce the problem in my environment. ]
- **Q3**: Do you have any other settings in bashrc or blerc? Does the problem reproduce without the other settings? [ This information is needed to check whether the problem is caused by interference with other settings. ]

> *From https://github.com/akinomyoga/ble.sh/issues/244#issue-1419836329*
> Then `ble.sh` gives the message that these keybindings are not recorgnized.

- **Q4**: What is the exact message for "the message" above? I tried to search for the string "recognized" (and a typo "recorgnized") in the ble.sh codebase, but ble.sh doesn't seem to output error/warning messages containing "recognized" and related to keybindings.

**Comment by E3D3** [comment] 2022-10-25 12:33
- The result of C-x C-v in `ble.sh` is

  > GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu) [Devuan GNU/Linux 4 (chimaera)]
  > ble.sh, version 0.4.0-nightly+a144ffa (noarch)
  > bash-completion, version 2.11 (sha1:b4ace8972c413e37d2d899f7a840b5fd7c042685, 76578 bytes) (noarch)
  > locale: LANG=en_US.UTF-8
  > terminal: TERM=xterm-kitty wcwidth=14.0-west/15.0-2+ri, kitty:0 (1;4000;26)

- I have in my _.bashrc_, besides the above listed first & last ble section
  ```
  #: Try ble.sh
  #:====================================================================
  #: I tried it for the first time on 20221020, and immediately liked
  #: its features but want to try it a little more before I decide if
  #: want to install : or not. Source it & it reloads Bash by itself.
  if test -f /home/e3d3/.e3progs/ble-nightly-20221001+a144ffa/ble.sh; then
      source /home/e3d3/.e3progs/ble-nightly-20221001+a144ffa/ble.sh
  fi
  ```

- The message I get when pressing `Alt-e` from within _emacs mode_ (my default)
  > unbound keyseq: M-e

**Comment by akinomyoga** [comment] 2022-10-25 13:13
Thanks for the information.

> * I have in my _.bashrc_, besides the above listed first & last ble section
>   ```
>   #: Try ble.sh
>   #:====================================================================
>   #: I tried it for the first time on 20221020, and immediately liked
>   #: its features but want to try it a little more before I decide if
>   #: want to install it or not.
>   if test -f /home/e3d3/.e3progs/ble-nightly-20221001+a144ffa/ble.sh; then
>       source /home/e3d3/.e3progs/ble-nightly-20221001+a144ffa/ble.sh
>   fi
>   ```

If I understand the above explanation correctly, this causes the behavior you observe. The above configuration means you load ble.sh twice, first with `--rcfile /your/ble--e3config` and second without specifying `--rcfile`. The second loading of ble.sh overwrites the settings made by the first loading. If you want to enable the keybindings, you need to specify rcfile to the second loading. But, to begin with, you don't need to load ble.sh twice. The later loading of ble.sh will cause the unloading of previously loaded ble.sh instances.

**Comment by akinomyoga** [comment] 2022-10-25 21:18
Thanks! Let me close the issue.

**Closed by akinomyoga** 2022-10-25 21:18 UTC
Labels: question
