### ISSUE TITLE
#advice message occasionally printed while typing

### ISSUE THREAD

**Issue by nik312123** [akinomyoga/ble.sh#251] opened 2022-11-17 20:08 UTC
**ble version**: 0.4.0-devel3+0c6291f
**Bash version**: 5.2.9(1)-release (aarch64-apple-darwin21.6.0)

I get the following message occasionally being printed when typing: `#advice: _parse_usage is not a function.`

It is very hard to replicate and is not super frequent. It seemed to happen more frequently in the duration immediately after I installed `ble.sh` and seemed to become less frequent the more I used it.

**Comment by akinomyoga** [comment] 2022-12-01 10:02
Sorry for the delay. I have been busy recently. I think I know the cause so fixed it in commit 267de7fe8ab542c10573dbdd7b973f9c080d67b3. Could you check if it solve the problem by updating ble.sh to the latest master using the command `ble-update` in a ble.sh session?

**Comment by nik312123** [comment] 2022-12-01 14:13
Seems to be fixed afaik. Will come back to this issue if it represents itself.

**Comment by akinomyoga** [comment] 2022-12-01 14:45
Thanks for trying! I'll later close it!

**Closed** 2022-12-03 01:27 UTC
