### ISSUE TITLE
Please Help installing it

### ISSUE THREAD

**Issue by danil0man** [akinomyoga/ble.sh#273] opened 2023-02-08 09:53 UTC
**ble version**: Is not installing
**Bash version**: 4.4.12(3)-release (x86_64-unknown-cygwin)

Hello. I am trying my best to install this but is not working. I get an error that the file does not exist
bash: /home/xxcastid/.local/share/blesh/ble.sh: No such file or directory
bash: /home/xxcastid/.local/share/blesh/ble.sh: No such file or directory

I have tried multiple ways to install it. I can clone the folder but is like the make does not make the file. Please help. I would love to have this feature, but since I am quite new I dont understand what I am missing for it to work. I would appreciate it alot

**Comment by akinomyoga** [comment] 2023-02-08 10:38
Thank you for trying ble.sh!

- **Q1**: What are the results of the following commands?

```bash
$ cygpath --version
$ cygcheck -c make
$ type make
$ make --version
```

- **Q2**: When you run the make command to build ble.sh, what are the outputs?

**Comment by akinomyoga** [comment] 2023-02-08 12:19
![image](https://user-images.githubusercontent.com/8982192/217526799-431efc4f-1eb5-4f95-b9a3-758cd3c9e8a1.png)

Hmm, This is so strange. Although `make` seems to be installed, it doesn't seem to function as expected. If `make` is working the following information should be output.

```bash
$ make --version
GNU Make 4.4
Built for x86_64-pc-cygwin
Copyright (C) 1988-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I'd like to check further information.

- **Q3**: What is the value of `$?` after running `make --version`? I.e., the result of the following command:

```bash
$ make --version
$ echo "$?"
```

- **Q4**: What are the outputs of the following commands?

```bash
$ ls -l /usr/bin/make
$ sha256sum /usr/bin/make
```

**Comment by danil0man** [comment] 2023-02-08 13:23
Q3
![image](https://user-images.githubusercontent.com/72052103/217542118-fbcf3306-ca10-4cde-8d32-13f050abb236.png)
I dont get any output

**Comment by danil0man** [comment] 2023-02-08 13:24
I am super confuse. specially since I am new to all this bash CLI

**Comment by akinomyoga** [comment] 2023-02-08 13:43
> * **Q3**: What is the value of `$?` after running `make --version`? I.e., the result of the following command:
> 
> ```shell
> $ make --version
> $ echo "$?"
> ```

Could you try this? You need to run `echo "$?"` after running `make --version`.

**Comment by danil0man** [comment] 2023-02-08 13:45
Q3
Sorry I missed this
![image](https://user-images.githubusercontent.com/72052103/217547186-2afdb49f-0a69-4ce4-ae39-d2fcb349e3c4.png)
Here it is

**Comment by akinomyoga** [comment] 2023-02-08 13:53
Thanks. Hmm, I've never met this situation. The situation is unusual. Don't worry, it's not just because you are new to the Bash CLI.

- **Q5**: How about these commands?

```bash
$ cygrunsrv -L
$ ps uax
$ mount
$ df
$ /usr/bin/make --version
$ /usr/make --version
```

**Comment by danil0man** [comment] 2023-02-08 13:57
Q5:
![image](https://user-images.githubusercontent.com/72052103/217549867-88e53433-0029-412b-978b-155dbc4a6cea.png)

Here are the commands and thx you for keeping up with the noob :D. Do you reckon it maybe have to do that I am running cygwin on windows and not in a linux dist?

**Comment by akinomyoga** [comment] 2023-02-08 14:04
Oh, there was a typo in the last command.

- **Q6**: Could you try the following?

```bash
$ /bin/make --version
```

> Do you reckon it maybe have to do that I am running cygwin on windows and not in a linux dist?

I recognize that you are in the Cygwin system, thanks to the Bash version information in your first report. All the commands "`cyg`-something" that I asked you to run are Cygwin related commands.

**Comment by danil0man** [comment] 2023-02-08 14:07
Q6.
![image](https://user-images.githubusercontent.com/72052103/217552624-92398b29-00a0-443c-b4ae-67e1428c3088.png)
Make dont seem to exist, I only get empty when i ask for the version of make

**Comment by danil0man** [comment] 2023-02-08 14:08
but when I try to install it I get it already exist
![image](https://user-images.githubusercontent.com/72052103/217553017-ec50ad00-9cc6-4f99-ba4b-7603f70cbe07.png)

**Comment by akinomyoga** [comment] 2023-02-08 14:13
> Do you reckon it maybe have to do that I am running cygwin on windows and not in a linux dist?

So, yes, I'm suspecting that it is related to some issue in the Cygwin system. The directory `/usr/bin` is not a physical Windows directory, but something virtually "mounted" by the Cygwin system. You will notice it if you look inside `C:\cygwin64\usr` within Explorer (the Windows default file manager).

Hmm, but `/bin/make --version` also fails, which means that the Cygwin `mount` is unrelated.

----

> Make dont seem to exist, I only get empty when i ask for the version of make

Yeah, I actually first suspected in Q3 that but it does seem to exist in https://github.com/akinomyoga/ble.sh/issues/273#issuecomment-1422594725.

----

In my experience, it is rare, but the Cygwin runtime information is broken internally. In that case, the problem would be fixed after I reboot the system. Could you try rebooting the system?

**Comment by danil0man** [comment] 2023-02-08 14:23
Yes, I can reboot my pc

**Comment by danil0man** [comment] 2023-02-08 14:27
Should I run the same commands from Q6?

**Comment by akinomyoga** [comment] 2023-02-08 14:27
Yes, Q6 `/bin/make --version` is sufficient to check!

**Comment by danil0man** [comment] 2023-02-08 14:29
![image](https://user-images.githubusercontent.com/72052103/217558479-8334b28e-68b0-4d69-b0ac-3d98c6b3d643.png)
nope. it did not do it with the reboot

**Comment by akinomyoga** [comment] 2023-02-08 14:31
OK, so, do you use`apt-cyg` to install packages in Cygwin? I've never tried `apt-cyg`, but the next thing I suspect is that the dependency resolution of packages might have failed.

- **Q7**: Could you check the output of the following command?

```bash
$ cygcheck make
```

**Comment by danil0man** [comment] 2023-02-08 14:32
Q7
![image](https://user-images.githubusercontent.com/72052103/217559545-ba1581e0-2efd-4aaf-b802-50d5342c9aea.png)

**Comment by danil0man** [comment] 2023-02-08 14:33
I tought that was the only way to install packages except pip3

**Comment by danil0man** [comment] 2023-02-08 14:45
that must be it then :(, do you know any workaround?
![image](https://user-images.githubusercontent.com/72052103/217562761-40ab2d03-53eb-45b0-9508-b19248ad2c36.png)
Once I installed cygwin I dont know how to add new packages without using apt-cyg

**Comment by danil0man** [comment] 2023-02-08 14:55
can I install make using chocolatey?

**Comment by akinomyoga** [comment] 2023-02-08 14:59
Hmm, so reinstalling doesn't fix the problem, which means that `apt-cyg` is somehow broken. I also find some issue report at https://github.com/transcode-open/apt-cyg/issues/110 about the dependency issue caused by `apt-cyg`, though it doesn't seem to happen frequently because this seems to be the only report.

> Once I installed cygwin I dont know how to add new packages without using apt-cyg

I guess this is the time you learn how to update existing packages and install new packages in an official way. Now I'm writing a description for you, wait a minute...

I've never used chocolatey, but I doubt the third-party controller could properly handle the Cygwin packages for every case. I'd guess it would work in the most cases, but rarely it could break the system. There is a reason that the official Cygwin provides a limited way of updating it.

**Comment by danil0man** [comment] 2023-02-08 15:03
I see, well, that sucked. I did not know, but you learn something new everyday. I perhaps then should reinstall cygwin. It seems if you reinstall and there is a file it understand is a modifcation instead of a full reboot. I will try

**Comment by akinomyoga** [comment] 2023-02-08 15:14
Ah, OK. Great!

**Comment by danil0man** [comment] 2023-02-08 15:14
Now it seems to be working
![image](https://user-images.githubusercontent.com/72052103/217570160-97658b96-316d-463d-95c3-5d80033fc569.png)
thx you so much I would not had know about apt-cyg and that i just need to reinstall to add new packages

**Comment by akinomyoga** [comment] 2023-02-08 15:17
Nice! One thing to note: It seems you have tried installing ble.sh multiple times, so you seem to have multiple lines of `source ~/.local/share/blesh/ble.sh` in your `~/.bashrc`. A single line is sufficient, so please open `~/.bashrc` in a text editor and remove duplicate lines of `source ~/.local/share/blesh/ble.sh`.

**Comment by danil0man** [comment] 2023-02-08 15:25
Yeah I manage to find were the lines were. Thx you. This is all new for me but amazing nonetheless. I cannot even phantom how you can make a whole program 😅

Skickat från Outlook för Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by danil0man** [comment] 2023-02-08 17:03
Hey Aki. 
Is working now
<img width="524" alt="image" src="https://user-images.githubusercontent.com/72052103/217600461-d6357295-45ef-44ee-8dfd-265efed1a44f.png">
thx for helping me out. I learned alot

**Comment by akinomyoga** [comment] 2023-02-08 23:33
OK! Thank you! Let me close the issue. If there is still an installation issue, please reopen it!

**Closed by akinomyoga** 2023-02-08 23:33 UTC
