### ISSUE TITLE
ble.sh & fzf completion for paths containing spaces

### ISSUE THREAD

**Issue by christianknauer** [akinomyoga/ble.sh#285] opened 2023-02-25 13:41 UTC
**ble version**: 
**Bash version**: 

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu) [Ubuntu 22.04.2 LTS]
ble.sh, version 0.4.0-devel3+10aa9b4 (noarch) [git 2.34.1, GNU Make 4.3, GNU Awk 5.1.0, API: 3.0 (GNU MPFR 4.1.0, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:b42f5d6a7ad6d4921ec73838ba54a96d6bd30936, 77071 bytes) (noarch)
fzf key-bindings, version +3364d4d1 (noarch) (integration: on)
fzf completion, version +3364d4d1 (noarch) (integration: on)
starship, version 1.12.0-master (rustc 1.65.0 (897e37553 2022-11-02), 2022-12-13 16:12:30 +00:00)
locale: LANG=de_DE.UTF-8 LC_TYPE=de_DE.UTF-8
terminal: TERM=tmux-256color wcwidth=14.0-west/15.0-2+ri, tmux:0 (84;0;0), unknown:- (0;136;0)

ble.sh surrounds the completion results of fzf (after a cd e.g.) with single quotes. At the same time fzf escapes all the necessary characters in the result. If the path contains a "problematic" character (space symbol, e.g.), the resulting argument passed to cd is broken.

Example:

# run the following commands
mkdir 'a b'
cd **(now press fzf trigger to init completion, typing ^a brings up the directory 'a b', select the directory)
# this completes to 
cd 'a\ b/'

**Comment by akinomyoga** [comment] 2023-02-27 02:52
Thank you for the report! I have pushed a fix 8965b61. Could you update ble.sh by running `ble-update` and check if the problem is solved? Thank you.

**Comment by akinomyoga** [comment] 2023-02-27 13:20
Thanks!

**Closed by akinomyoga** 2023-02-27 13:20 UTC
Labels: compatibility
