### ISSUE TITLE
[konsole drag&drop] Drag&drop function to terminal

### ISSUE THREAD

**Issue by ciranus** [akinomyoga/ble.sh#211] opened 2022-07-19 06:55 UTC
**ble version**: 0.4.0-devel2+276baf2 
**Bash version**: 5.1.16 (x86_64-pc-linux-gnu)

**Problem**: when a function block is dropped from a text editor to terminal, each line is immediately analyzed, and then errors reported.
note: this problem does not exist in zsh.

**Proposal**: when dropping a function to terminal, ble.sh should detect a function declaration line, and wait the end of the function block before reporting any error.

**Test** : drag and drop a basic function to terminal

```
f1() { echo A
}
```

Or is there any configuration tricks to make it work ?

**Comment by akinomyoga** [comment] 2022-07-19 08:40
Thank you for the report! But it doesn't reproduce in my environment. `ble.sh` is supposed to work as you expect. Maybe this is related to the behavior of your terminal in pasting texts (e.g., it directly writes `\n` in the pasted text) or the keybinding settings.

- **Q1**: What is your terminal?
- **Q2**: What is the result of the following commands?

```bash
$ ble/debug/keylog#start
$      <-- (paste a small function)
$ ble/debug/keylog#end
```

- **Q3**: Do you set up custom keybindings for <kbd>C-m</kbd>, <kbd>C-j</kbd>, or <kbd>RET</kbd>?
- **Q4**: What is the result of the following command?

```bash
$ ble-bind -P | grep 'C-[mj]'
```

**Comment by ciranus** [comment] 2022-07-19 08:53
**A1**: konsole (kde)

**A2**: 
```
===== bytes =====
102 49 40 41 32 123 32 101 99 104 111 32
 65 10 125 10 192 155 91 50 48 48 126 98
 108 101 47 100 101 98 117 103 47 107 10
1 121 108 111 103 35 101 110 100 192 155
 91 50 48 49 126 13

===== chars =====
f 1 ( ) SP { SP e c h o SP A LF } LF ESC
 [ 2 0 0 ~ b l e / d e b u g / k e y l o
 g # e n d ESC [ 2 0 1 ~ RET

===== keys =====
f 1 ( ) SP { SP e c h o SP A C-j } C-j p
aste_begin C-m
```
**A3** : no custom bindings / just default

**A4**: 
```
ble-bind -P | grep 'C-[mj]'
ble-bind -m 'isearch' -f 'C-j' 'isearch/accept-line'
ble-bind -m 'isearch' -f 'C-m' 'isearch/exit'
ble-bind -m 'nsearch' -f 'C-j' 'nsearch/accept-line'
ble-bind -m 'nsearch' -f 'C-m' 'nsearch/exit'
ble-bind -m 'emacs' -f 'C-j' 'accept-line'
ble-bind -m 'emacs' -f 'C-m' 'accept-single-line-or-newline'

```

**Comment by ciranus** [comment] 2022-07-19 09:50
Ok thanks.
I'm currently switching back from zsh default shell to bash5, thanks to ble.sh that I lately discovered just few days ago !

**Comment by akinomyoga** [comment] 2022-07-20 09:22
I confirmed the behavior of Konsole. It seems GNOME terminal also behaves the same behavior. On the other hand, XTerm and Alacrity do not seem to accept drag & drop. From this observation, I guessed that this drag & drop feature is implemented in each terminal but not something translated to keyboard inputs by a lower layer like the window manager.

Then I have checked the source code of Konsole. In the present version of `konsole`, the dropped text seems to be [directly written to the PTY](https://github.com/KDE/konsole/blob/f7a05efac0c63722ae90aa123dd43863a602cbe9/src/terminalDisplay/TerminalDisplay.cpp#L2767). This is actually not an expected behavior by terminal applications. The binary representation of <kbd>C-j</kbd> (LF) in the terminal communication conflicts with the naive encoding of newlines in texts. Normally, in the terminal communication, newlines are represented by RET (\r), so we need to normalize different representations of newlines in text, such as `\n` and `\r\n`, to `\r`. Konsole seems to [correctly handle it for the pasted text](https://github.com/KDE/konsole/blob/f7a05efac0c63722ae90aa123dd43863a602cbe9/src/terminalDisplay/TerminalDisplay.cpp#L2227-L2234). It also handles the bracketed paste mode and other sanitization of the pasted text. I believe the dropped text should also undergo all of these processes of sanitization, newline adjustments, and the addition of bracketed-paste markers.

I have also checked the source code of GNOME terminal to find that they actually have supported these processes for dropped text recently in commit [f5f15e67](https://github.com/GNOME/gnome-terminal/commit/f5f15e67492ac61ebe664c5ea12377eedb41f112#diff-ae84c335cd03fee86a173ad097991eb61ac324a2e2fadced3a26f050e9d1e55b). The current `master` of GNOME terminal first receives the dropped text in [`terminal_screen_drag_data_received()`](https://github.com/GNOME/gnome-terminal/blob/5d5c1f74979c9e81da449b593b17e31e6d14e1f4/src/terminal-screen.cc#L1966-L1968). Then the text is relayed through [`terminal_screen_paste_text()`](https://github.com/GNOME/gnome-terminal/blob/5d5c1f74979c9e81da449b593b17e31e6d14e1f4/src/terminal-screen.cc#L2346), [`vte_terminal_paste_text()`](https://github.com/GNOME/vte/blob/0a663194fc1d4c9f5c2f952f6ccfea8a8a4719f7/src/vtegtk.cc#L2839), [`vte::terminal::Widget::paste_text()`](https://github.com/GNOME/vte/blob/0a663194fc1d4c9f5c2f952f6ccfea8a8a4719f7/src/widget.hh#L383), and [`vte::terminal::Terminal::widget_paste()`](https://github.com/GNOME/vte/blob/master/src/vte.cc#L5479) and finally arrives in [`vte::terminal::pastify_string()`](https://github.com/GNOME/vte/blob/0a663194fc1d4c9f5c2f952f6ccfea8a8a4719f7/src/pastify.cc#L43). The adjustments of LF is processed in [`pastify_string`](https://github.com/GNOME/vte/blob/0a663194fc1d4c9f5c2f952f6ccfea8a8a4719f7/src/pastify.cc#L81-L85). The bracketed paste is also processed [there](https://github.com/GNOME/vte/blob/0a663194fc1d4c9f5c2f952f6ccfea8a8a4719f7/src/pastify.cc#L50-L55).

I will later test the following patch and submit it to the upstream of Konsole:

https://invent.kde.org/akinomyoga/konsole/-/commit/d1f59a63fd6e71c049a9963118f7cfa92087a102

**Comment by ciranus** [comment] 2022-07-20 09:33
Thanks for your time. This is far beyond my skills.
However, `zsh` is able to bypass this issue I have never seen before using bash as default shell.
I then suppose `zsh` found a solution to force bracketed paste protection.

I also tried to add `set enable-bracketed-paste on`  to `.bashrc` with no effect.

**Comment by akinomyoga** [comment] 2022-07-20 10:01
> I then suppose `zsh` found a solution to force bracketed paste protection.

`zsh` and plain `bash` are not affected by this behavior of Konsole because they treat <kbd>C-j</kbd> the same as <kbd>RET</kbd> / <kbd>C-m</kbd> by default. However, ble.sh assigns different roles to <kbd>C-j</kbd> and <kbd>RET</kbd> / <kbd>C-m</kbd>. This is the reason ble.sh is affected. The same problem also arises in other terminal applications that assign different roles to <kbd>C-j</kbd> and <kbd>RET</kbd> such as `list-interactive-mode` of GNU Emacs.

If you would like to do drag&drop frequently, you can change the keybinding of <kbd>C-j</kbd> to the same target as <kbd>RET</kbd> as a temporary workaround, but in that case, there is no way to execute the command line in the multiline editing mode. So you need to sacrifice another key combination for the command execution in the multiline mode. For example, <kbd>M-RET</kbd> (decoded as <kbd>C-M-m</kbd>) inserts a newline in the command line by default, but we may change this to execute the command line instead.

```bash
# blerc

# Tentative workaround for Konsole
ble-bind -f C-j accept-single-line-or-newline
ble-bind -f C-M-m accept-line
```

> I also tried to add `set enable-bracketed-paste on` to `.bashrc` with no effect.

It's already turned on by `ble.sh` by default unless the user explicitly disables it, so it wouldn't actually change the setting. By the way, the setting `set enable-bracketed-paste on` needs to be written in `~/.inputrc`. If you would like to put it in `.bashrc`, you can write as

```bash
# bashrc

bind 'set enable-bracketed-paste on'
```

**Comment by ciranus** [comment] 2022-07-20 10:16
> ```shell
> # Tentative workaround for Konsole
> ble-bind -f C-j accept-single-line-or-newline
> ble-bind -f C-M-m accept-line
> ```

It nearly solves !
Remaining problem: (RET or C-m: insert a newline, C-j: run) -> no way to execute `run`.

![ksnip_20220720-121215](https://user-images.githubusercontent.com/61602511/179958048-62225db2-a893-4875-83cf-5173e62edfba.jpg)

**Comment by akinomyoga** [comment] 2022-07-20 10:32
> no way to execute `run`.

Yes, so this:

> For example, <kbd>M-RET</kbd> (decoded as <kbd>C-M-m</kbd>) inserts a newline in the command line by default, but we may change this to execute the command line instead.

i.e., `ble-bind -f C-M-m accept-line`. With this keybinding, you should be able to run the command by pressing <kbd>M-RET</kbd> or <kbd>C-M-m</kbd>.

**Comment by ciranus** [comment] 2022-07-20 10:41
> you should be able to run the command

No way.
However `bleopt term_bracketed_paste_mode=off` is not understood by 0.4.0.
[ble.sh/blerc at master · akinomyoga/ble.sh](https://github.com/akinomyoga/ble.sh/blob/master/blerc)

**Comment by akinomyoga** [comment] 2022-07-20 11:11
> 0.4.0-devel2+276baf2

Ah, wait. I have been thinking that you are using the latest devel version, but you are actually using the version two years ago. Could you update it to the latest version by running `ble-update`?

> No effect with any bash config (.bashrc ou .xinputrc).
> By reading [Paste behavior altered after update to Konsole 20.12.0-1 • KDE Community Forums](https://forum.kde.org/viewtopic.php?f=227&t=169160&p=440855&hilit=bracketed+paste#p440855), how to test disabling enable-bracketed-paste with ble ?

How did you test that it doesn't have effect? The dropped text will never be affected in the current version of Konsole because Konsole just doesn't support the bracketed paste mode for the dropped text. It only supports the bracketed paste mode for the pasted text.

> > you should be able to run the command
> 
> No way.

Hmm, that's different from the behavior I observe in my environment.

**Q5**: Which version of Konsole do you use?

```bash
$ konsole --version
konsole 21.12.2
```

**Q6**: Also, what would be inserted when you press <kbd>C-v</kbd> and then <kbd>M-RET</kbd>?

```bash
$ echo [press C-v M-RET]^[^M
```

> However `bleopt term_bracketed_paste_mode=off` is not understood by 0.4.0.

It's not supported by the old version devel2+276baf2. Also, to turn off the bracketed paste in the latest devel version (i.e., `master`) of ble.sh, the value should be empty.

```bash
bleopt term_bracketed_paste_mode=
```

> [ble.sh/blerc at master · akinomyoga/ble.sh](https://github.com/akinomyoga/ble.sh/blob/master/blerc)

The above is `blerc` template for `master`. The template for `v0.4.0-devel2` is this: [ble.sh/blerc at v0.4.0-devel2](https://github.com/akinomyoga/ble.sh/blob/v0.4.0-devel2/blerc).

**Comment by akinomyoga** [comment] 2022-07-20 11:45
> `konsole 22.04.3`
> new test with `ble.sh 20220712+1c7f7a1`

Thanks.

> No  way to tun the command with `.blesh` modification.

You need to put settings in `~/.blerc` but not in `~/.blesh`.

Could you try **Q6** in [my above reply](https://github.com/akinomyoga/ble.sh/issues/211#issuecomment-1190143261)?

> However, if `bash+konsole` or `zsh+konsole` do not have drag&drop issue, but the issue starts with ble.sh enabled, I wonder if something should not be investigated in blesh code.

I already know the cause as I have already described in [my reply](https://github.com/akinomyoga/ble.sh/issues/211#issuecomment-1190078718). As I have already described, it's just because ble.sh assigns different roles to <kbd>C-j</kbd> and <kbd>RET</kbd> while `zsh` and plain `bash` assigns the same role.

**Comment by ciranus** [comment] 2022-07-20 11:51
> `~/.blerc` but not in `~/.blesh`

Typo. Sorry. In fact I use `~/.config/blesh/init.sh` (as proposed as update somewhere).

`echo [press C-v M-RET]^[^M`
`[press C-v M-RET]^[^M`

**Comment by ciranus** [comment] 2022-07-20 12:00
```
===== bytes =====
13 98 108 101 47 100 101 98 117 103 47 1
07 101 121 108 111 103 35 101 110 100 13

===== chars =====
RET b l e / d e b u g / k e y l o g # e 
n d RET

===== keys =====
C-m b l e / d e b u g / k e y l o g # e 
n d C-m

```

**Comment by ciranus** [comment] 2022-07-20 12:06
Wait wait ......

```
Without .blerc modif:
===== bytes =====
13 192 155 91 50 48 48 126 98 108 101 47
 100 101 98 117 103 47 107 101 121 108 1
11 103 35 101 110 100 192 155 91 50 48 4
9 126 13

===== chars =====
RET ESC [ 2 0 0 ~ b l e / d e b u g / k 
e y l o g # e n d ESC [ 2 0 1 ~ RET

===== keys =====
C-m paste_begin C-m
```
with:
```
ble-bind -f C-j accept-single-line-or-newline
ble-bind -f C-M-m accept-line
```

===== bytes =====
13 192 155 91 50 48 48 126 98 108 101 47
 100 101 98 117 103 47 107 101 121 108 1
11 103 35 101 110 100 192 155 91 50 48 4
9 126 192 155 91 50 48 48 126 98 108 101
 47 100 101 98 117 103 47 107 101 121 10
8 111 103 35 101 110 100 192 155 91 50 4
8 49 126 127 127 127 127 127 127 127 127
 127 127 127 127 127 127 127 127 127 127
 127 127 13
===== chars =====
RET ESC [ 2 0 0 ~ b l e / d e b u g / k 
e y l o g # e n d ESC [ 2 0 1 ~ ESC [ 2 
0 0 ~ b l e / d e b u g / k e y l o g # 
e n d ESC [ 2 0 1 ~ DEL DEL DEL DEL DEL 
DEL DEL DEL DEL DEL DEL DEL DEL DEL DEL 
DEL DEL DEL DEL DEL RET
===== keys =====
C-m paste_begin paste_begin C-? C-? C-? 
C-? C-? C-? C-? C-? C-? C-? C-? C-? C-? 
C-? C-? C-? C-? C-? C-? C-? C-m

```

**Comment by ciranus** [comment] 2022-07-20 12:18
Finally, with
```
ble-bind -f C-j accept-single-line-or-newline
ble-bind -f C-M-m accept-line
```

`run` command can be activated with `Alt+RET`

**Comment by akinomyoga** [comment] 2022-07-20 12:23
~~Thanks. In every case, <kbd>M-RET</kbd> seems to be just encoded as `RET` in your environment. But <kbd>M-RET</kbd> is supposed to be encoded as e.g. `ESC RET`, and in fact, it is encoded as `ESC RET` in my environment.~~

~~Hmm, I don't have an idea. Maybe Meta/Alt is stolen by a lower layer in your environment, or you might have special keyboard settings of Konsole.~~

~~Can I try another approach? Could you add the keybinding of~~

Oh, have you finally solved the problem?

**Comment by ciranus** [comment] 2022-07-20 12:30
> Oh, have you finally solved the problem?

I would say it's a workaround I would have never been able to imagine with your `ble-bind` proposal.
Now I would suggest that a much cleaner solution is investigated so that ble.sh is more compatible with `konsole`.
`ble.sh` should not break what works 100% fine with `default  bash` or `zsh` and `konsole`.
Really a specific ble.sh issue.
Thanks.

**Comment by akinomyoga** [comment] 2022-07-20 12:41
> Now I would suggest that a much cleaner solution is investigated so that ble.sh is more compatible with `konsole`.

This is a bug of Konsole so should be fixed in Konsole as I have already written. This is the clean solution.

> `ble.sh` should not break what works 100% fine with `default bash` or `zsh` and `konsole`.

It's just accidental that `zsh` and plain `bash` are not affected; ble.sh hits the quirk of Konsole just because ble.sh provides a different feature set than `zsh` and plain `bash`.

> Really a specific ble.sh issue.

It's not a specific issue to ble.sh as I have already written. I'm not interested in surveying and creating a complete list of affected terminal applications, but for example, `lisp-interactive-mode` of GNU Emacs is also affected as I have already written.

**Comment by akinomyoga** [comment] 2022-07-20 13:48
> Ok, then let's say that a custom tweaking is necessary for kde/konsole users.

Yes, and that's the *raison d'être* of `ble-bind`. I'd keep it open until I test the patch for Konsole and submit it. Thank you for your report!

**Comment by ciranus** [comment] 2022-07-28 14:59
For information:
* new test made with same bash+konsole versions
* `ble.sh 0.2.5_50116`

`C-j` default key combination to `run` in multiline mode works out of the box, with no configuration at all.

**Comment by akinomyoga** [comment] 2022-07-28 15:04
What do you mean? Isn't it the same behavior as ble-0.3 and ble-0.4? Without custom configurations, <kbd>C-j</kbd> has always been "run" in the multiline editing mode.

**Comment by ciranus** [comment] 2022-07-28 15:10
> Isn't it the same behavior as ble-0.3 and ble-0.4?

No, because I need your specific `.blerc` keyboard modification for both 0.3 & 0.4  to enable `run` command with `Alt+RET`.
No other solution identified.

> Without custom configurations, C-j has always been "run" in the multiline editing mode.

Humm. No, because I would have open this issue !
This only works for me with `C-j` by default with 0.2.5.

**Comment by akinomyoga** [comment] 2022-07-28 16:00
Huh? Everything is wrong. You seem to be already forgetting the original reason that you have opened the issue. The issue is not that "<kbd>C-j</kbd> cannot be used to run the command in the multiline editing mode". The original issue is that "the multiline command that has been dragged and dropped into Konsole is run unexpectedly." and is present in all of the versions of ble.sh from 0.1 to 0.4 including 0.2.5, and this is caused by the implementation of Konsole.

- If you want to work around the problem of Konsole's drag and drop, you need to rebind <kbd>C-j</kbd> in your configuration in all the versions of ble-0.1..0.4 including 0.2.5. In this case, you cannot use <kbd>C-j</kbd> to run the command in the multiline editing mode even in 0.2.5.
- If you don't need to work around the problem of Konsole's drag and drop, you can use any of ble-0.1..0.4 including 0.2.5 without any custom configurations. In this case, you can always run the command in the multiline editing mode by pressing <kbd>C-j</kbd>. Instead, the original problem of Konsole's drag and drop is present.

Anyway, all of the versions of ble.sh, 0.1..0.4, behave exactly the same in Konsole in this regard, and the difference you observe is just because of the difference in your configuration.

**Comment by ciranus** [comment] 2022-07-28 16:30
You are right. Sorry for this 0.2.5 test disturbance.
When discovering ble.sh few days ago, my first test was directly `drag&drop` of a function: it did not work.
. first step : enable the multiline feature (stop breaking line by line)
. second step: enable the run command.
I did not test & notice before that C-j was OK by default when entering a function line by line.
Anyway, it was an opportunity for me to discover that 0.2.5 feature level is enough for my need (with lower memory requirement).

**Comment by akinomyoga** [comment] 2022-09-09 10:35
The PR to the upstream `konsole` [konsole!714](https://invent.kde.org/utilities/konsole/-/merge_requests/714) was merged a month ago, but it doesn't seem to be released until the next KDE release, which I guess would be around next March. I initially thought I could keep open this PR until the fix is released, but let me close this now as it would seem to take half a year. Anyway, thank you for the report!

**Closed by akinomyoga** 2022-09-09 10:35 UTC
Labels: compatibility, External Bug
