### ISSUE TITLE
unrecognized CSI sequence: ESC [ D

### ISSUE THREAD

**Issue by korongmambu** [akinomyoga/ble.sh#122] opened 2021-06-30 13:38 UTC
**ble version**: 0.3.3+7fa584c
**Bash version**: 5.1.8(1)-release

After install ble.sh via aur terminal always show "unrecognized CSI sequence: ESC [ D" every time when new session opened.

**Comment by akinomyoga** [comment] 2021-06-30 13:43
Thank you for the report.

- What is your terminal?
- What is your operating system?

**Comment by korongmambu** [comment] 2021-06-30 13:51
My terminal is konsole, my OS is archlinux, and when left key is pressed nothing happened.

**Comment by korongmambu** [comment] 2021-06-30 13:52
The message "unrecognized CSI sequence: ESC [ D" is above my prompt

**Comment by korongmambu** [comment] 2021-06-30 13:54
Also when I pressed f11 show "unbound keyseq: f11"

**Comment by akinomyoga** [comment] 2021-07-01 20:13
Sorry for the blank. I have set up Arch and installed konsole, but cannot reproduce it.

> Also when I pressed f11 show "unbound keyseq: f11"

When I press the key <kbd>f11</kbd>, my konsole seems to toggle between the window mode and the full-screen mode. Is your terminal really konsole? Or do you configure the keybindings of konsole?

> and pressed esc show "unbound keyseq: C-M-[".

How many times did you press <kbd>esc</kbd>? `C-M-[` corresponds to double <kbd>esc</kbd>s. If you pressed <kbd>esc</kbd> only once, here's also some problem.

Also, does the problem reproduce with a plain Bash without any other user configurations?

```bash
$ INPUTRC=/dev/null bash --norc     # <--- Start a plain Bash session
$ source /path/to/ble.sh --norc --noinputrc    # <--- Load ble.sh
```

**Comment by korongmambu** [comment] 2021-07-02 03:45
> When I press the key f11, my konsole seems to toggle between the window mode and the full-screen mode. Is your terminal really konsole? Or do you configure the keybindings of konsole?

I'm sorry it's my fault, when I press f11 it was in yakuake (another terminal program) not konsole. Btw it's work in konsole (with f11) and yakuake (with ctrl+shift+f11) like you said (toggle window mode to full-screen) and no "message".

> How many times did you press esc? C-M-[ corresponds to double escs. If you pressed esc only once, here's also some problem.

Four times, does not appear when less than that.

> Also, does the problem reproduce with a plain Bash without any other user configurations?

I try set up my `~/.bashrc` like in [set-up-bashrc](https://github.com/akinomyoga/ble.sh#set-up-bashrc) without other setting, the message in new session is gone but still there when press esc four times and f11 on yakuake.

> ```shell
> $ INPUTRC=/dev/null bash --norc     # <--- Start a plain Bash session
> $ source /path/to/ble.sh --norc --noinputrc    # <--- Load ble.sh
> ```

I tried what you suggested too, same as above. But when sourcing `ble.sh` show:
```shell
ble.sh: unrecognized argument '--norc'
ble.sh: unrecognized argument '--noinputrc'
```

P.S. I thought pressing esc will remove the complete sugesstion but it did'nt.

**Comment by akinomyoga** [comment] 2021-07-02 09:25
> > When I press the key f11, my konsole seems to toggle between the window mode and the full-screen mode. Is your terminal really konsole? Or do you configure the keybindings of konsole?
> 
> I'm sorry it's my fault, when I press f11 it was in yakuake (another terminal program) not konsole. Btw it's work in konsole (with f11) and yakuake (with ctrl+shift+f11) like you said (toggle window mode to full-screen) and no "message".

OK, thank you! I'll try it later in yakuake. Anyway, the message `unbound keyseq: f11` is actually the expected behavior. This tells us that `f11` doesn't cause any operations in the line editor.

> > How many times did you press esc? C-M-[ corresponds to double escs. If you pressed esc only once, here's also some problem.
> 
> Four times, does not appear when less than that.

OK, this is actually somehow an expected behavior. ESC can be specially handled in the transmission, so four escapes might be reduced or might be pending somewhere.

> > Also, does the problem reproduce with a plain Bash without any other user configurations?
> 
> I try set up my `~/.bashrc` like in [set-up-bashrc](https://github.com/akinomyoga/ble.sh#set-up-bashrc) without other setting, the message in new session is gone

This means that the new-session error message is caused by the interference between ble.sh and the other settings.

> but still there when press esc four times and f11 on yakuake.

They are expected.

> I tried what you suggested too, same as above. But when sourcing `ble.sh` show:
> 
> ```shell
> ble.sh: unrecognized argument '--norc'
> ble.sh: unrecognized argument '--noinputrc'
> ```

Oh, sorry. I forgot that you are using ble-0.3. These options are available from ble-0.4. Anyway, we've already confirmed that the problem is caused by the interference with the other settings, now we no longer have to test it with a plain Bash.

> P.S. I thought pressing esc will remove the complete sugesstion but it did'nt.

By default, <kbd>C-g</kbd> can be used to cancel various operations (auto-complete, menu-complete, isearch, lastarg, dabbrev, etc.). If you want to use <kbd>ESC</kbd> for cancellation you may put the following settings in your `.blerc`:

```bash
# In ~/.blerc (or ~/.config/blesh/init.sh, etc.)

ble-bind -m isearch -f 'C-[' isearch/cancel
ble-bind -m isearch -f 'ESC' isearch/cancel
ble-bind -m lastarg -f 'C-[' lastarg/cancel
ble-bind -m lastarg -f 'ESC' lastarg/cancel

function blerc/complete-load.hook {
  ble-bind -m auto_complete -f 'C-[' auto_complete/cancel
  ble-bind -m auto_complete -f 'ESC' auto_complete/cancel
  ble-bind -m menu_complete -f 'C-[' menu_complete/cancel
  ble-bind -m menu_complete -f 'ESC' menu_complete/cancel
  ble-bind -m dabbrev       -f 'C-[' dabbrev/cancel
  ble-bind -m dabbrev       -f 'ESC' dabbrev/cancel
}
blehook/eval-after-load complete blerc/complete-load.hook
```

Also, when you want to have keybindings of `ESC`, maybe you also need to set up corresponding timeouts. See [user-contents](https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A73-Key-Binding#user-content-sec-esc-reception)

> P.P.S Oh, I use oh-my-bash too.

OK, I also try it with `oh-my-bash` later.

**Comment by akinomyoga** [comment] 2021-07-03 00:51
OK, I could reproduce it with `oh-my-bash` and identified the problem. I'll later fix it.

**Comment by akinomyoga** [comment] 2021-07-04 03:26
@korongmambu I have pushed a fix 742777e to `v0.3-master` branch. Could you update `ble.sh` by `ble-update` and see if the problem has been fixed?

**Comment by korongmambu** [comment] 2021-07-05 06:16
> Could you update ble.sh by ble-update and see if the problem has been fixed?

You mean run `ble-update` in terminal? I try run it, but show message:
```
~ $ ble-update
/usr/bin/mkdir: cannot create directory ‘/usr/share/blesh/src’: Permission denied
[ble: exit 1]
```

So I use sudo:
```
~ $ sudo ble-update
sudo: ble-update: command not found
[ble: exit 1]
```

Try search with `which`:
```
~ $ which ble-update
which: no ble-update in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
[ble: exit 1]
```

Also no `ble-update` in `/usr/share/blesh`:
```
~ $ ls -lah /usr/share/blesh
total 436K
drwxr-xr-x   4 root root 4,0K Jun 30 10:46 .
drwxr-xr-x 267 root root  12K Jul  2 11:06 ..
-rw-r--r--   1 root root 411K Jun 30 10:46 ble.sh
drwxr-xr-x   2 root root 4,0K Jun 30 10:46 keymap
drwxr-xr-x   2 root root 4,0K Jun 30 10:46 lib
```

Because I installed from AUR: 
- I think I have to manually update and edit PKGBUILD right?
- But, what should I change?
- Just change `pkgrel` and add [742777e](https://github.com/akinomyoga/ble.sh/commit/742777e770a8ce22aa76f67cb042f89feb34d631) to the `source` in PKGBUILD is enough?

Sorry for being silly.

**Comment by akinomyoga** [comment] 2021-07-05 23:23
Ah, OK. I think I need to release the next version 0.3.4 later, but I want to port related patches from v0.4 to v0.3 before that, so it'll take some time.

- For the time being, as you said, I think you may edit PKGBUILD.
- Or, another way is to load `ble.sh` in a `root` Bash interactive session and run `ble-udpate`.
- Even another way is to switch to [AUR blesh-git](https://aur.archlinux.org/packages/blesh-git) though it is sometimes unsatble.


> * Just change `pkgrel` and add [742777e](https://github.com/akinomyoga/ble.sh/commit/742777e770a8ce22aa76f67cb042f89feb34d631) to the `source` in PKGBUILD is enough?

I haven't tested it, but If you are going to edit PKGBUILD, I think you should edit PKGBUILD as something like this:

```diff
diff --git a/PKGBUILD b/PKGBUILD
index 040dad8..90741f2 100644
--- a/PKGBUILD
+++ b/PKGBUILD
@@ -2,14 +2,14 @@ pkgname=blesh
 _pkgname=ble.sh
 pkgdesc="A replacement for bash's line editor with advanced features"
 pkgver=0.3.3
-pkgrel=1
+pkgrel=2
 license=(BSD)
 conflicts=(blesh-git)
 url='https://github.com/akinomyoga/ble.sh'
 depends=(bash)
 arch=(any)
-source=("https://github.com/akinomyoga/ble.sh/releases/download/v0.3.3/ble-${pkgver}.tar.xz")
-sha256sums=('a7e66383bd828584e82133ee08ab0bd8074ef0a739eacb835ff0970c3853f33a')
+source=("git+$url.git#commit=742777e770a8ce22aa76f67cb042f89feb34d631")
+sha256sums=('SKIP')
 install=blesh.install

 package() {
```

**Comment by korongmambu** [comment] 2021-07-06 06:27
> * Or, another way is to load `ble.sh` in a `root` Bash interactive session and run `ble-udpate`.

Ah it's work in `root` environment, silly me haha. Also the message in new session is gone now, thank you very much.

**Comment by akinomyoga** [comment] 2021-07-06 06:44
Great! Thank you for testing!

And sorry for the inconvenience of the updating. [ FYI: This is the limitation of ble.sh v0.3. `ble-update` is actually handled better in 0.4 (devel version) so that `ble-update` in the user's Bash sessions works properly with AUR helpers. Also, it provides a way to update it without entering the interactive session through `bash /path/to/ble.sh --update`. #108 is the related discussion. ]

Are there any other problems? If everything works fine, you may close the issue now. Thank you!

**Closed** 2021-07-06 07:07 UTC
