### ISSUE TITLE
Slow typing on macOS

### ISSUE THREAD

**Issue by beaugunderson** [akinomyoga/ble.sh#59] opened 2020-07-29 19:09 UTC
**ble version**: commit f7dc47796f98cd6fadc37b40b0adcb658f9731e3
**Bash version**: 5.0.17(1)-release, x86_64-apple-darwin19.4.0
**macOS version**: 10.15.6

Creating a new issue per https://github.com/akinomyoga/ble.sh/issues/58#issuecomment-665809475 :)

Very slow when typing; so far I tried:

- `bleopt complete_auto_history=` in `~/.blerc`
- `complete -r`

**Comment by akinomyoga** [comment] 2020-07-29 19:27
Thank you!

In the following checks, please hold the following settings.

```bash
bleopt complete_auto_history= in ~/.blerc
complete -r
```

Q1 First I would like to check if it is caused by auto-complete or not. Is the response still slow with the following setting?

```bash
bleopt complete_auto_complete=
```

Q2 Also, is the speed of the response changed by the context? For example, does the speed change between `ech@` and `echo hell@` (where `@` indicates the cursor position)?

**Comment by akinomyoga** [comment] 2020-09-26 07:46
ping @beaugunderson: Just reporting "it is slow" without further information does not help. If you will not provide further information on the problem, could you please close this issue?

**Comment by akinomyoga** [comment] 2020-10-23 12:15
ping @beaugunderson

**Comment by akinomyoga** [comment] 2020-11-24 07:16
@beaugunderson No reply at all. Let me close this issue.

**Closed by akinomyoga** 2020-11-24 07:16 UTC
Labels: Waiting for OP, performance
